### ISSUE TITLE
Windows activation docs migration

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#104]
>> Kann es sein, dass diese Seite noch nicht in die neue Doku übernommen wurde?
>>
>> https://www.linuxmuster.net/wiki/dokumentation:handbuch:clients:individualactivation
>
> Ja, korrekt.
> Keinerlei Aktivierungsmechanismen sind in sphinx dokumentiert.
>
> Kannst du  - wenn nicht gleich die Doku schreiben - Rückmelden, ob diese
> Seite noch so funktioniert? 

ich habe das Heute so durchgeführt für 3 Lenovolaptops mit einem Win7 Image.
Es hat bei allen drei so funktioniert wie dort beschrieben.

Ich halte es nicht für nötig die Anleitung zu modifizieren.
Ich meine, das kannst du so in die Doku übernehmen.

- ebenso: Volumenaktivierung usw aus der selben Quelle

**Comment by toheine** [comment]
Fehlt das immer noch in der Doku? Ich habe es auf jeden Fall nicht gefunden. Wenn gewünscht würde ich mich der Doku annehmen.

**Comment by jolly-jump** [comment]
Klar. Ist halt Windows. Kann aber in die Doku. Entscheide selbst, ob das Priorität hat.

**Comment by cweikl** [comment]
Wie ist hier der Stand?
