### ISSUE TITLE
manual: schulkonsole teacher 

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#105]
Manual for the Schulkonsole for teachers is missing/incomplete:
http://docs.linuxmuster.net/de/latest/manuals/schulkonsole-teacher/index.html

Add 
- [x] current room features
- [ ] class features
- [ ] projects features

take from the Basiskurs (http://docs.linuxmuster.net/de/basiskurs/basiskurs.html) what is necessary

**Comment by toheine** [comment]
Könnte geschlossen werden ... da Bezug auf alte Schulkonsole und nicht aktuelle Web-Ui

**Comment by jolly-jump** [comment]
weg damit
