### ISSUE TITLE
Screenshots akutalisieren für neue Schulkonsole und neues Linbo (blau)

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#106]
- [x] http://docs.linuxmuster.net/de/latest/release-information/schulkonsole.html
- [x] http://docs.linuxmuster.net/de/latest/release-information/linbo.html
- [x] http://docs.linuxmuster.net/de/latest/howtos/windows10clients/registration.html
- [x] http://docs.linuxmuster.net/de/latest/howtos/windows10clients/startconf.html
- [x] http://docs.linuxmuster.net/de/latest/howtos/windows10clients/windows10installation.html
- [ ] http://docs.linuxmuster.net/de/latest/howtos/printer/2-drucker-hinzufuegen.html
- [ ] http://docs.linuxmuster.net/de/latest/howtos/printer/4-drucker-zugriffssteuerung.html
- [x] http://docs.linuxmuster.net/de/latest/howtos/manage-users/verwalten.html und ff.

- [x] http://docs.linuxmuster.net/de/latest/manuals/schulkonsole-admin/linbo.html

- [x] http://docs.linuxmuster.net/de/latest/manuals/schulkonsole-admin/repair.html

- [x] http://docs.linuxmuster.net/de/latest/howtos/preparation-newterm/index.html

- [x] http://docs.linuxmuster.net/de/latest/howtos/use-internet-in-class/index.html

- [x] http://docs.linuxmuster.net/de/latest/howtos/use-files-in-class/index.html

- [x] http://docs.linuxmuster.net/de/latest/howtos/print-student-passwords/index.html

- [x] http://docs.linuxmuster.net/de/latest/howtos/change-student-passwords/index.html

- [x] docs.linuxmuster.net/de/latest/howtos/check-own-quota/index.html

- [ ]

**Comment by aloisr** [comment]
Erledigt am 28.12.2017

**Comment by jolly-jump** [comment]
Danke, Alois!!!
