### ISSUE TITLE
Weiterführende Dokumentation zu linuxclients

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#111]
Suche weiterführende Dokumentation zu http://docs.linuxmuster.net/de/latest/howtos/linuxclients/index.html
und füge sie hier ein:
http://docs.linuxmuster.net/de/latest/howtos/linuxclients/outlook.html

**Comment by MachtDochNix** [comment]
both Links [(url) http://docs.linuxmuster.net/de/latest/howtos/linuxclients/outlook.html link is dead] and [http://docs.linuxmuster.net/de/latest/howtos/linuxclients/outlook.html] dead

Can this be closed?

**Comment by cweikl** [comment]
yes, according to the new documentation for the new linuxmuster-linuxclient7 package.
