### ISSUE TITLE
Vorwort über linuxmuster.net schreiben

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#123]
target:

http://docs.linuxmuster.net/de/v7/about/about.html

source:

* http://www.linuxmuster.net/wikiarchiv/dokumentation:overview
* https://www.linuxmuster.net/de/ueber/
* http://www.linuxmuster.net/wikiarchiv/dokumentation:handbuch:preparation:features
* http://docs.linuxmuster.net/de/basiskurs/basiskurs/preface.html
  
Bitte feststellen, wo duplizierte Daten unbedingt nötig sind und mit diesen Quellen synchron halten

target technische Infos:

unterhalb von http://www.linuxmuster.net/wikiarchiv/dokumentation:techsheets

Hilfreiche Infos:

* http://www.linuxmuster.net/wikiarchiv/dokumentation:sphinx 
* http://www.linuxmuster.net/wikiarchiv/dokumentation:handbuch_zum_handbuch

**Comment by jolly-jump** [comment]
Seid ihr damit fertig? 
Ich könnte meine obigen Links noch gegenchecken, ob man darauf noch Infos extrahiert bzw. dort (Homepage, wikiarchiv) Infos reparieren müsste.

**Comment by MachtDochNix** [comment]
I've already done something there, so please check it out:

[Was ist linuxmuster.net](https://docs.linuxmuster.net/de/latest/about/about.html)
vs.
[Einführung](https://docs.linuxmuster.net/de/latest)

By and large, the introduction contains only links to the complete documentation. But this is shown in the left column anyway. I consider it unnecessary or could be replaced by "What is ... ".

**Comment by jolly-jump** [comment]
Ja, das Ticket ist älter als die Einführung von MachtDochNix. Ich vermute, dass das wegkann, habs aber nicht mehr gegengelesen.

**Comment by toheine** [comment]
I've read both sides. Both good... also the introduction with the links.This is redundant... but that doesn't hurt at this point. I would leave it like this and close the issue. Agreed?

**Comment by MachtDochNix** [comment]
I took another look at it too. I'd want to take the links out after all. They have no informational content or bring no advantage to the chosen reader.

So something like this:

![index](https://user-images.githubusercontent.com/16538354/86591746-6e9af180-bf92-11ea-8879-a89d846360d9.png)


You know linuxmuster.net, then link to the first item of the installation guide.

Otherwise link to What is linuxmuster.net

**Comment by toheine** [comment]
That's fine for me.

**Comment by MachtDochNix** [comment]
If there are no objections then I will change it to this. I need a little more time because the school year is coming to an end.

**Comment by toheine** [comment]
there's no hurry ;-)

**Comment by MachtDochNix** [comment]
reference to  

Version releases
known errors and their correction
Linking Forum

[https://ask.linuxmuster.net/t/doku-braucht-evtl-bug-fix-abschnitt/5819/24?u=machtdochnix]()
