### ISSUE TITLE
Dokumentation Schulkonsole v7

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#124]
bislang keine Dokumentation bekannt, 
target: eigentlich http://docs.linuxmuster.net/de/v7/about/release-information/schulkonsole.html

wenn aber alles neu ist, kann man nur die neuesten Features erwähnen und auf die hauptsächliche Doku verweisen, die dann hier stehen sollte:
http://docs.linuxmuster.net/de/v7/school-console/index.html

**Comment by cweikl** [comment]
Einfache Dokumentation der WebUI aus Lehrer und aus global-admin Sicht eingestellt (Essen 2019 Arbeitstagung)

**Comment by cweikl** [comment]
global-admin: http://docs.linuxmuster.net/de/v7/systemadministration/schoolconsole/index.html
and http://docs.linuxmuster.net/de/v7/user-management/manage-users/index.html
teacher: http://docs.linuxmuster.net/de/v7/user-management/student-management.html
and http://docs.linuxmuster.net/de/v7/user-management/change-teacher-passwords/index.html
and http://docs.linuxmuster.net/de/v7/user-management/manage-quota/index.html
