### ISSUE TITLE
Installation on XEN: anpassen für 7.0

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#129]
target:

http://docs.linuxmuster.net/de/v7/installation/install-on-xen/index.html

source:

unbekannt, @netzint ?

Abstimmung mit issue #130  wg. Bildern

**Comment by cweikl** [comment]
Hi,
sollen wir weiterhin eine solche Anleitung anbieten ? Falls ja, wäre es sinnvoll auf die OpenSource Alternatve XCP-ng zu wechseln und hierfür die Anleitung zu erstellen. Was ist mit der Anleitung für kvm, die ja in 6.2 neu als Alternative aufgenommen wurde ?
VG
Chris

**Comment by netzint** [comment]
Hi Chris,

du hast ja bereits Erfahrung mit XCP-ng gemacht und sogar eine XenOrchestra VM erstellt. Ich denke es wäre gut wenn du hierfür eine Anleitung erstellen könntest. Ich hatte mal an einem Skript für XenServer gearbeitet mit Online VM-Repo, Backup und Autostart Funktionen. Leider habe ich das im letzen Jahr nicht mehr verfolgt da ich mit der V7 Entwicklung beschäftigt war/bin. Diese Toolbox ist aber auch nicht entscheidend. Würdest du hier vielleicht eine Anleitung erstellen auf Basis XCP und XO?

Wir arbeiten auch immer mehr mit Proxmox. Hier sollte auch mal bei Gelegenheit eine Anleitung erstellt werden. Dies kann aber gerne aus der Community übernommen werden.

Durch das prepare-skript ist es ja nun einfach vorgefertigte VMs/Appliances zu erstellen. 

VG, Maurice

**Comment by cweikl** [comment]
Hallo Maurice,
ok, ich habe heute mal mit der Doku für XCP-ng angefangen. Als Administrationsalternative haben wir bislang ja auch OpenXen Manager  unter Linux dargestellt. Allerdings unter 18.04 taucht folgendens Problem auf, so dass die Installation via Paketquellen so nicht möglich ist:

Paketlisten werden gelesen... Fertig
W: GPG-Fehler: http://pkg.netzint.de bionic InRelease: Die folgenden Signaturen waren ungültig: 0E24CAB4AE10FDA04CE6FA2B1A216CA15B04BB2D

Ich fände es gut, wenn wir nochmal ein SupplementalPack.iso mit unserern v7 VMs zur Verfügung stellen. Wie hast Du die erstellt, hast Du dazu noch das Script oder selbst zusammengestellt.
Ich würde sonst mal aus der bestehenden Testinstallationen mit den VMs versuchen ein SupplementalPack zu bauen.

Dadurch verkürzen wir die Zeit bis zur Inbetriebnahme.

VG
Chris

**Comment by netzint** [comment]
Hi Chris,

XenServer hat ihr einiges umgestellt in der SupplementalPack erstellung weshalb das alte Paket so unter neueren Versionen nicht oder nur bedingt funktioniert. Wir haben hier aber etwas in der Pipeline. 

Was zunächst mal genügen würde sind VMs die das Prepare erfahren haben (inkl. VM-Tools) sowie eine XO (selbstbau) VM.  Wenn du das bereistellen könntest würde ich versuchen dies in eine Disk o.ä. zu erstellen.

Wir sollten diesen Thread aber in ASK fortsetzen. 

VG,

Maurice
