### ISSUE TITLE
Server Installation für 7.0 anpassen

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#130]
target:

- http://docs.linuxmuster.net/de/v7/getting-started/serverinstallation/index.html

source:

- https://github.com/linuxmuster/linuxmuster-base7/wiki/Setup-und-Inbetriebnahme-des-Systems

Abstimmung mit issue #129 wg. Bildern

**Comment by MachtDochNix** [comment]
Can this be closed?

**Comment by cweikl** [comment]
Yes
