### ISSUE TITLE
caption in toctree untranslateable

### ISSUE THREAD

**Issue by zefanja** [linuxmuster-docs/main#135]
Using captions in toctrees looks nice, but their are some problems:
* their are not translated (maybe thats fixed in a more recent version of sphinx)
* https://github.com/sphinx-doc/sphinx/issues/3169

So I suggest to put all the Table of content in one main toctree.

**Comment by jollyzsher** [comment]
Don't get it: what is wrong with the nice looking toctree...
if not, it looks like this: 
![screenshot](https://user-images.githubusercontent.com/2824334/33636379-23dd93e0-da1c-11e7-9b4f-a8cec0bf683c.png)

I understand, translation is a problem, ok.
But how can we make it look nicer than *that* flat?

Anyway, I'll check it in.

**Comment by zefanja** [comment]
Fixed in 649fd11
