### ISSUE TITLE
linuxmuster.net  Coovachilli - Benutzersteuerung + Schulkonsole in 6.2

### ISSUE THREAD

**Issue by jollyzsher** [linuxmuster-docs/main#136]
see https://ask.linuxmuster.net/t/coovachilli-benutzersteuerung-schulkonsole-in-6-2/443/22?u=tobias

Hallo Tobias,

entweder ist meine Installation fehlerhaft oder die Doku zu 6.2 an einer Stelle zumindest irreführend:

http://docs.linuxmuster.net/de/latest/release-information/schulkonsole.html#verwaltung-wlan1

“Die Verwaltung des WLAN-Zugriffs erfolgt intern über ein spezielles Projekt. Standardmäßig heißt das Projekt p_wifi. Es wird angelegt, falls es bei der Installation nicht existiert. Der Projektname kann über die Schulkonsole des administrator unter Einstellungen geändert werden.”

Ich habe zuerst in der Schulkonsole nach dem Projekt p_wifi gesucht und nichts gefunden. Danach habe ich mal versuchsweise das Wlan für eine Klasse in der Schulkonsole freigeschaltet/gesperrt und konnte dann an der Konsole mit “sophomorix-project -i -p p_wifi” die Änderungen beobachten. Scheint also alles zu funktionieren. Nur eine Änderung des Projektnamens geht (bei mir?) nicht, warum auch.

**Comment by MachtDochNix** [comment]
Ich habe die betreffende Zeile gelöscht. Auch bei meinem System habe ich keine Möglichkeit in der Schulkonsole gefunden, eine Änderung vorzunehmen.
