### ISSUE TITLE
v7 edit on github does not work

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#137]
http://docs.linuxmuster.net/de/v7/

"edit on github" leitet auf eine 404:

https://github.com/linuxmuster-docs/main/blob/origin/v7/source/index.rst

the "origin" somehow got in there. don't know why

**Comment by jolly-jump** [comment]
found the problem related to: https://github.com/rtfd/readthedocs.org/issues/1820

Problem is I don't understand how RTD thinks the versioning should work.
Why is "basiskurs" working anyway? I don't get it.

Tobias

**Comment by jolly-jump** [comment]
weird:
I have set up a new docs fork:
http://linuxmuster-fork.readthedocs.io/en/latest/
all the branches that I activated I am not able to "edit on github", weird is that the same thing in the original works for "basiskurs" branch:
http://docs.linuxmuster.net/de/basiskurs/
but the "edit on github" link links still to the "all-of-me"-github-repo.

I suspect that RTD broke the "edit on github" link along the timeline since "basiskurs" was created and shown.

I give up for now: the simplest way to debug the v7-documentation is to remove the "origin" in the URL.

**Comment by zefanja** [comment]
You should delete your fork soon, because it will show up in google soon. That's what happend to my fork, too. 

I've read about that problem, too. I'll try to find a way to fix it.

**Comment by jolly-jump** [comment]
thanks for the tip.

**Comment by jolly-jump** [comment]
This was somehow fixed. Probably with the new template changes of #139
