### ISSUE TITLE
adapt read-the-docs  template (for v7 especially)

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#139]
- [x] Add an "v7" Tag to the "Docs" root-breadcrumb
- [x] add an "7.0" in a different color in the "versions" field.
- [x] also annoying: custom css is not used when not on rtd.

I could not override the template using these instructions:
- http://www.sphinx-doc.org/en/stable/templating.html
- https://stackoverflow.com/questions/44154226/how-do-i-customize-sphinx-rtd-theme-default-search-settings#44175925
- http://www.sphinx-doc.org/en/stable/theming.html
- https://stackoverflow.com/questions/23211695/modifying-content-width-of-the-sphinx-theme-read-the-docs

**Comment by zefanja** [comment]
@jolly-jump  I've committed a first draft using the bootstrap theme. You can have a look here: http://docs.linuxmuster.net/de/v7/

IMO there is problem: the table of content in the sidebar reflects only the current page, not the subpages.

We could solve that in two ways: using another theme (http://www.writethedocs.org/guide/tools/sphinx-themes/) and adopt it to our needs (custom css). We could stick with the default RTD theme.

Or change our document structure so that we have on file per main chapter. This could be done with the `include` directive but needs adjusting of paths.

**Comment by jolly-jump** [comment]
@zefanja :+1:  that looks really good on first sight.

Solving the problems from the POV "What do we want?"
- I do not like that the RTD-Theme does not show good navigation on a long page
- I like to have a similar look "top menu" as in Wiki/website/ask.linuxmuster.net, preferably with those as links

If both is possible with customizing the RTD-Theme we could stick.
Especially: If the page is really long, the sidebar showing the local page navigation gets long then the screenheight and then again

**Comment by jolly-jump** [comment]
This is how the navbar looks like, when I simulate a mobile view on a desktop in RTD-theme:
![grafik](https://user-images.githubusercontent.com/2824334/34649461-2617b548-f3b0-11e7-84fe-4aac527b7502.png)

It is weird, but it works at least.

**Comment by zefanja** [comment]
I've adjusted the default theme to fit our requirements. If it is ok, we can close this issue. 

Local testing with custom CSS is possible, if you install the sphinx_rtd_theme locally.

> -1 for the RTD-theme: the navbar does not stick around during normal reading in desktop mode, though you can scroll the navbar separately

What do you mean or what behaviour do you expect? There is an option `sticky_navigation` for the theme (https://github.com/rtfd/sphinx_rtd_theme#project-wide-configuration)

> -1 for the RTD-Theme: when I simulate mobile view by narrowing the firefoxwindow so that the navbar disappears, I get the top menu with navigation which does not stay when I scroll down.

That's true. Depending on the screen size this is a bug or feature :)

**Comment by jolly-jump** [comment]
> Local testing with custom CSS is possible, if you install the sphinx_rtd_theme locally.

works to build, but does not show the custom breadcrump, e.g.
It does show the "7.0" in orange in the sidebar on top, but on readthedocs it shows "v7" (the branch name, I guess)

>  >    -1 for the RTD-theme: the navbar does not stick around during normal reading in desktop mode, though you can scroll the navbar separately
>
> What do you mean or what behaviour do you expect? There is an option sticky_navigation for the theme (https://github.com/rtfd/sphinx_rtd_theme#project-wide-configuration)

If I open a chapter like "using the leoclient" where the articles are quite long and I would like to navigate inside the article or subchapter, the navbar: rather than showing the current chapter, die toctree "slides along" which makes absolutely no sense.
Yes, I now tried "sticky_navigation=False" again, and yes, this is better: the toctree stays where it was and at least navigating through the headlines within one page it stays fixed on the left.
But: using sticky_navigation=False seems to fail to  open any menu when I simulate a small window width, *and* it would be nice, if the navigation would stay fixed on a chapter and not only within a page -> feature request to sphinx_rtd_theme, I guess.

2nd wish request: using the template, I guess we could have a top lmn-bar as well :), right?
minor thing: I don't like "Docs" in the breadcrumps:

 I would use:
`<li><a href="{{ pathto(master_doc) }}">{{ version }}</a> &raquo; </li>`
rather than:
`<li><a href="{{ pathto(master_doc) }}">{{ _('Docs') }}</a> &raquo; {{ version }} &raquo;</li>`

but since this does not work using a local build, I only guess, this should work on readthedocs.

cheers

**Comment by zefanja** [comment]
> but since this does not work using a local build, I only guess, this should work on readthedocs.

It does :) Make your you have installed the theme (`pip install ...`) and also make sure to have the latest sphinx version (`pip install sphinx --upgrade`) (1.6.3 at the moment). Then it should work, although I have to run `make clean` before every build.

Then everything works locally like on RTD.

**Comment by jolly-jump** [comment]
Thanks, upgrading the theme worked.
I pulled in the sticky_navigation = False and maybe we can both check what happens on smartphones/tablets?

If it doesn't work we will live with stricky_navigation= True.
Cheers

**Comment by jolly-jump** [comment]
Sorry, once again:
current status: sticky_navigation = False in v7 and = True in "latest":
I can't see how the toctree behaves differently, see
http://docs.linuxmuster.net/de/v7/clients/leoclient2/leo2-erweiterungen.html
http://docs.linuxmuster.net/de/latest/clients/leoclient2/leo2-erweiterungen.html

when you scroll down both behave the same: the toctree of the current chapter disappears.
When you click on an index within the page, like:
http://docs.linuxmuster.net/de/latest/clients/leoclient2/leo2-erweiterungen.html#vm-windows-xp-tipps-und-tricks
or
http://docs.linuxmuster.net/de/v7/clients/leoclient2/leo2-erweiterungen.html#vm-windows-xp-tipps-und-tricks
it works as I expect it (in both cases of sticky_navigation):
the toctree stays fixed, even if I scroll down.

So, beside the point that sticky_nav seemingly does not matter when I read on readthedocs, the toctree *probably* would behave much more user-friendly, if we had one page per chapter
(which ironically comes close to your proposal for the bootstrap theme:
> Or change our document structure so that we have on file per main chapter. This could be done with the include directive but needs adjusting of paths.
I would say: one file per howto, e.g. one "leoclient.rst", one "install-on-xen", etc. those would be large pages then.
)

**Comment by zefanja** [comment]
IMO it is not a big deal with the sidebar. It is not perfect, but as a user you may use the previous / next buttons. 

One page per chapter will make a difference, because the page does not need to be reloaded if you want to go to a specific section in that chapter (and so the side won't jump to the top).

> 2nd wish request: using the template, I guess we could have a top lmn-bar as well :), right?

Should this top bar stick at the top or do you want it to scroll with the content?

**Comment by jolly-jump** [comment]
> One page per chapter will make a difference, because the page does not need to be reloaded if you want to > go to a specific section in that chapter (and so the side won't jump to the top).
> 

we'll keep this in mind we remake pages, maybe in  future versions :)

> >    2nd wish request: using the template, I guess we could have a top lmn-bar as well :), right?
>
> Should this top bar stick at the top or do you want it to scroll with the content?

stick at the top? I dunno. That's how it is with the top bar in the wiki and the forum and even the homepage.

**Comment by MachtDochNix** [comment]
Can this be closed?

**Comment by cweikl** [comment]
I think so, yes.
