### ISSUE TITLE
Restructure v6.2 to look like v7.0

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#150]
since [cherry-pick](https://ask.linuxmuster.net/t/fragen-rund-um-git/1623/7) might work for when the file structure is basically the same, I suggest restructureing v6.2 now. Thorsten voted for it as well.

this makes it easier to adapt and reuse v7 and v6.2 commits.
Tobias

**Comment by jolly-jump** [comment]
waiting for community  here: https://ask.linuxmuster.net/t/dokumentation-v7-und-v6-2-in-neuer-struktur/1572/4?u=tobias

**Comment by jolly-jump** [comment]
Aaaand forgot: what about the translation.
I don't really know how this works: the po-files probably get newly created, the english strings are probably gone(?) and how do we *not* loose the 50% already translated?
help!

**Comment by zefanja** [comment]
Transifix saves all the translation but the assignment / relation is maybe lost. You need to assign in again buy hand. That also happens if someone changes the source string. I can take care of it.

**Comment by jolly-jump** [comment]
Ok, thanks. Tell me, if this blocks merging the v6.2 branch with the master branch.
Otherwise I would merge it as soon as we agreed upon it in ask

**Comment by zefanja** [comment]
For me it is fine. I'll update the translations asap, but not before the weekend.
