### ISSUE TITLE
Lernvideo(s) erstellen

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#168]
1. Einfachst: bei github anmelden und kleinigkeiten ändern, rst-sprache
2. komplexer: VM runterladen und installieren, dokumentation lokal bauen, git fork erstellen, master-master pull-request erstellen
3. git fork lokal, git clone, git pull, git commit, git push, pull-request
4. git: mit fehlern umgehen: commit rückgängig? git log, git checkout.  unversionierte Dateien löschen? git clean
5. eigenen Branch pro issue erstellen, git checkout -b fix-123, commit, push, pull-request

**Comment by toheine** [comment]
Verstehe ich das richtig: Wir machen ein kleines Video wie der Workflow auf github ist?

**Comment by jolly-jump** [comment]
Das kann man machen.
Kam damals auf, als in der v6 einer der Michaels so Videos für die Doku erstellt hat.
Es legt die Schwelle sicher niedriger, mitzumachen, aber ich glaube, dass es meist nicht an der Komplexität liegt, sondern an der Zeit...

**Comment by jolly-jump** [comment]
Das hier wurde eingebracht:
https://docs.linuxmuster.net/de/v6/systemadministration/install-on-kvm/install.html
und da kam die Idee von jemand, das für den Workflow bei github bzw. lokal mit git zu machen, damit man es einfacher hat, in der Doku etwas zu verbessern.
Für Punkt 1 in der Liste lohnt sich das vermutlich schon.

**Comment by toheine** [comment]
Jep ... kann man ja machen und schauen ob es was bewirkt. Wenn die Issues und Milestones ein wenig aufgeräumt sind mache ich ein kurzes Video.
