### ISSUE TITLE
Description "Gast-WLAN mit Gutschein / Voucher" is not complete

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#169]
main/source/systemadministration/network/unifiwifi/unifivoucher.rst

It is missing how to set up a WIFI network for the guest portal.

Es fehlt wie man ein WIFI-Netz für das Gastportal einrichtet.

**Comment by jolly-jump** [comment]
Hallo @aloisr,

wenn du wieder da bist, kannst du dir das ja vielleicht vormerken.
Ich habe davon weder die Ahnung noch hab ich es jemals eingerichtet.

VG, Tobias

**Comment by toheine** [comment]
Ist das noch aktuell für LMN7?

**Comment by cweikl** [comment]
This has already been written for v7: https://docs.linuxmuster.net/de/latest/external-services/unifiwlan/unifivoucher.html
