### ISSUE TITLE
Update from 6.2 to 7 or comment out

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#200]
The following parts should be updated or have to be commented out:

- [x] Die Checkliste: http://docs.linuxmuster.net/de/v7/getting-started/prerequisites/index.html#checkliste
- [x] Linuxmuster-chilli: http://docs.linuxmuster.net/de/v7/systemadministration/network/coovawifi/index.html seems to be outdated - how is it replaced?
- [x] obviously -sadly - Schulkonsole: http://docs.linuxmuster.net/de/v7/appendix/school-console/index.html

**Comment by cweikl** [comment]
New checklist for v7: http://docs.linuxmuster.net/de/v7/getting-started/prerequisites.html

New chapter for using a freeradius on opnsense for connecting APs and other hosts. -> to be decided weather we write an additional chapter for connecting a WLAN solution - we have to be aware of the fact that we do not support special vendor solutions !

Basic usage of the new schoolconsole in v7 online.
