### ISSUE TITLE
Server Installation v7 from scratch

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#201]
target: 

- http://docs.linuxmuster.net/de/v7/appendix/install-from-scratch/index.html

source:

- find out, DIY

low priority, but very useful for everyone

**Comment by cweikl** [comment]
There is a chapter for proxmox addressing a from scratch installation:

http://docs.linuxmuster.net/de/v7/appendix/install-on-proxmox/index.html
