### ISSUE TITLE
migration via sophomorix dokumentieren

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#209]

**Comment by jolly-jump** [comment]
@jeffbeck .  Ich kann zeitnah deine Migration ausprobieren und dokumentieren. Kannst also mal drüber gucken, hier wird das Resultat sein:

http://docs.linuxmuster.net/de/v7/systemadministration/maintenance/migration.html

**Comment by jeffbeck** [comment]
Please wait with the migration documentation at least until 5.12.18

**Comment by jeffbeck** [comment]
Die Migration ist nun getestet und korrigiert und somir bereit für die Dokumentation

Bei letzten Schritt `What else to do by hand` kann noch einiges dazukommen.

Wie ist denn das gedacht, bekommst du mit, wenn sie auf

https://github.com/linuxmuster/sophomorix4/wiki/Migration

was ändert? Und suchst dir das aus den diffs raus?

**Comment by jolly-jump** [comment]
DAs könnten wir so tun, wenn das z.B. so lange gilt bis die v7 raus ist. Wenn das ein darüberhinaus gehender Workflow sein soll, dann sollte das vllt. anders sein. Es gilt ja auch für linuxmuster-linbo etc.

**Comment by jolly-jump** [comment]
Hi @jeffbeck , 

ich habe die Migration migriert und ist online:
http://docs.linuxmuster.net/de/v7/systemadministration/maintenance/migration.html

Folgende :fixme: werde ich durch ausprobieren nicht herausbekommen:

- In Schritt 3 werden Benutzer migriert, vorerst ohne WebUI/SELMA Rechte.
Werden in Schritt 8 mit dem sophomorix-update jetzt alle Rechte gesetzt, oder muss noch etwas manuell gemacht werden?

- In Schritt 4 verstehe ich den  Satz nicht: 

> Test if firstpasswords work: (At this stage only some should work, according your password policy)
>     # sophomorix-passwd --test-firstpassword

ich habe es so verstanden: Abhängig von den bisherigen Passwortregeln werden nicht mehr alle Erstpasswörter nach den neuen Regeln funktionieren

- In Schritt 9: ist der rooms-bug noch aktuell? ist das relevant? ich weiß nicht, worum es geht.

**Comment by cweikl** [comment]
Documented migration has been tested by users. Therore, new issues should be opened if any further fixes are necessary.
