### ISSUE TITLE
Add Maintenance and release schedule

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#231]
see https://docs.nextcloud.com/server/15/admin_manual/release_schedule.html
and update latest version automatically

**Comment by jolly-jump** [comment]
https://docs.nextcloud.com/server/18/admin_manual/release_schedule.html

ich habs mal implementiert und in ask zur Diskusison gestellt:
https://ask.linuxmuster.net/t/lmn6-und-lmn7-wann-und-wann-nicht-mehr/5879

**Comment by MachtDochNix** [comment]
Close of the issue must have been left behind. Herewith made up for.
