### ISSUE TITLE
kvm/proxmox snapshot strategy

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#246]
- [x] take and merge snapshots (go back to snapshotted state)
- [x] take and remove snapshots (for usage as a backup with minimal downtime)
- [ ] needs example for snapshot of lmn7-server
- [ ] needs good example for a complete disaster recovery (/etc/libvirt etc.)
- [ ] needs the same for proxmox, if different

**Comment by jolly-jump** [comment]
Ich habe jetzt das Snapshotten dokumentiert, zumindest um ein LVM zurückzusetzen mit ``mergesnapshot``, siehe #247

**Comment by jolly-jump** [comment]
Ich habe jetzt das Snapshotten dokumentiert, zumindest um ein LVM zurückzusetzen mit ``mergesnapshot``, ebenso ein Backup und ein Vollbackup mittels qemu-img, siehe #247, #248, #249

Habe die Ideen von hier übernommen: http://www.linuxmuster.net/wiki/anwenderwiki:virtualisierung:kvm:kvm_ubuntu1204

**Comment by cweikl** [comment]
Issue for community Wiki.
