### ISSUE TITLE
"Virtualisierung mit XCP-ng" > "Download-Quellen" VM Download link inkorrekt

### ISSUE THREAD

**Issue by Yekohama** [linuxmuster-docs/main#250]
![screenshot](https://user-images.githubusercontent.com/48986865/55070715-27336f00-5087-11e9-8a23-406d0a1bb2d0.png)

Der link zu den VMs in den Download-Quellen ist nicht vorhanden bzw sind auf der linuxmuster seite keine VMs für XCP-ng zu finden

**Comment by cweikl** [comment]
fixed for v6.2 and v7 beta.
