### ISSUE TITLE
/var/linbo/linbofs64.lz enthält start.conf wird nicht von pxe geladen

### ISSUE THREAD

**Issue by YunusEmreKirmizikan** [linuxmuster-docs/main#278]
Die `start.conf` habe ich seltsamerweise in der Datei `/var/linbo/linbofs64.lz` gefunden aber trotz veränderung wurde es nicht übernommen. 

Die `start.conf` sollte ja eigentliche über pxe geladen werden, wird jedoch nach einer neuinstallation einer VM überhaupt nicht mehr geladen. 

Kommt es evtl von der Netzint Toolbox, dass sich die start.conf jetzt in der linbofs64 befindet?

Und wie kann ich die entsprechende Datei neu generieren?

**Comment by baumhof** [comment]
Hallo Yokohama,

hier wird die Dokumentation von linuxmzster.net gepflegt.
Probleme werden im Forum besprochen unter ask.linuxmuster.net.
Poste deine Probleme lieber dort: dann hast du eine größere Chance, dass du Antworten auf deine Fragen erhälst.
:-)

LG

Holger
