### ISSUE TITLE
Link zu Schulverwaltungs Exporten

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster-docs/main#300]
Hoffentlich bin ich hier richtig zur Doku für die V7?

Ich habe einen Link im sophomorix-Quellcode der auf die Benutzerexports der Schulverwaltungsprogramme verweist und ins nun ins Leere geht:

http://www.linuxmuster.net/wiki/dokumentation:sophomorix:svp_atlantis

Datei https://github.com/linuxmuster/sophomorix4/blob/bionic/sophomorix-samba/filter/atlantis-csv-listenauswahl.filter

Wo finden sich denn nun die Schulverwaltungprogramm Exportanleitungen?

LG, Rüdiger

**Comment by jolly-jump** [comment]
Hi Rüdiger, 
wie soll ich das verstehen? Die Exportanleitungen *waren* wohl im anwenderwiki. Wenn sie nicht mehr dort sind, hast du sie doch wo anders hinverschoben, oder nicht?
Vermutlich nicht, sonst wüsstest du es ja.
Hier ist jedenfalls das Archiv:
https://wiki.linuxmuster.net/archiv/dokumentation:sophomorix:schulverwaltungsprogramme
VG, Tobias

**Comment by cweikl** [comment]
is this still an issue?

**Comment by MachtDochNix** [comment]
I would feel it important to place the link to the wiki with the system administration. So I'll reopen the issue.

**Comment by cweikl** [comment]
Im Wiki finden sich die Seiten hier: https://wiki.linuxmuster.net/community/anwenderwiki:verwaltungsnetz:start
Dies sind sehr veraltet. Eine Doku zu den Exporten der Verwaltungsprogrammen dürfte schwierig sein. Aus den Bundesländern könnten die linuxmuster.net user im Wiki hier einen neuen Bereich bestücken ...

Daher schließe ich das Ticket für die Doku.
