### ISSUE TITLE
lmn v7 "unbewachten" IP-Bereich nach Installation dicht machen beschreiben.

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#347]
https://ask.linuxmuster.net/t/v7-neuinstallation-auf-proxmox/4831/33

Hintergrund der ganzen Geschichte war, dass oft der Proxy nicht direkt ordentlich lief nach der Installation. Ohne Internetzugang fühlten sich viele Nutzer anschließend verloren.
Darüber hinaus muss am Client auch erstmal der Proxy eingestellt werden.

Ich halte es nicht für Gefährlich diesen kleinen IP Bereich standardmäßig offen zu lassen bis er manuell deaktiviert wird.

**Comment by cweikl** [comment]
Gute wäre zu wissen, an welchen Stellen in der Doku dies umgesetzt werden soll.
ggf. hier: http://docs.linuxmuster.net/de/v7/getting-started/prerequisites.html

und dann bei allen Beschreibungen zu den Virtualisierungsumgebungen 
wie z.B.
http://docs.linuxmuster.net/de/v7/getting-started/installoptions/install-on-proxmox/index.html

**Comment by MachtDochNix** [comment]
Ich würde sagen ganz unten!

Nach der Aufnahme des ersten Clients. Ab dann könnte eine Installation ja in den produktiven Einsatz gehen. Eventuell ein neues Kapitel "Installation absichern"?!

**Comment by jolly-jump** [comment]
Hi, 
"Installation absichern" klingt sinnvoll. Meines Erachtens gehört auch noch dazu, sich zu überlegen, von wo aus der Virtualisierer denn erreichbar sein sollte.
Manche stellen ihn ja in ROT um von außen drauf zu kommen. Manche stellen ihn aber *auch* in GRÜN um einfach an den Server etc. zu kommen.
ICh bin mir nicht sicher, was wir raten sollten, evtl. noch mal im ask asken.

**Comment by michaelkohls** [comment]
Wie wäre es mit einem Hinweis am Ende von hier:
https://docs.linuxmuster.net/de/latest/systemadministration/network/default-access-rules.html

**Comment by MachtDochNix** [comment]
Da passt das schon rein. Aber ich würde es lieber sehen, dass wir das in die geführte Installation bringen. Siehe WIKI (https://github.com/linuxmuster-docs/main/wiki/List-of-links-according-to-the-installation-flowchart)
Also noch eine extra Seite/Box vor dem eigentlichen Ende der Installation

In der von Micha genannten Seite sollte auf alle ein Hinweis zum Schließen der "Sicherheitslücke" sein. Ist es eigentlich eine? Hieß es nicht der Zugriff über die Nutzeraccounts geregelt? Oder wird genau das hiermit ausgehebelt?

Fragen über Fragen

**Comment by MachtDochNix** [comment]
Noch dazu Zitat #494 von michaelkohls:
"Aber irgendwie ist das kaum von Bedeutung. Dazu müsste erstmal einer drauf kommen, dass es diesen Bereich gibt und es schaffen ein Gerät mit einer solchen Adresse in's grüne Netz zu bringen. Und das nur um am Proxy vorbei zu kommen."

Nix leichter als das. Guckst du in die tollste Beschreibung der lmn-Welt und dann IP manuell setzen bei deinem Client. Oder irre ich mich schon wieder?

**Comment by michaelkohls** [comment]
Haste durchaus recht. Die Info zu finden ist sicher kein Problem. Jedoch sollte ein Nutzer (Schüler oder Lehrer) im grünen Netz nicht so einfach berechtigt sein, seine IP zu ändern. Normal arbeitet ja niemand mit Admin Rechten. Am einfachsten geht es noch mit einem eigenen Gerät, welches an eine freie Dose angestöpselt wird. 
Ich dachte nur, dass der erreichbare Erfolg (freier Internetzugang) nicht sooo groß ist, dass jemand das macht. Aber es stimmt schon: Einen gibt es immer, dem es das wert ist.

Alles in allem muss es schon als Sicherheitslücke betrachtet werden. Somit ist es gut, wenn man am Ende der Installation darauf hingewiesen wird. Der Internetzugriff wird ja nur dann über die Nutzeraccounts geregelt, wenn diese auch den Proxy benutzen und nicht dran vorbei kommen.

**Comment by michaelkohls** [comment]
Habe erstmal den Hinweis an der Stelle "https://docs.linuxmuster.net/de/latest/systemadministration/network/default-access-rules.html" verfasst. Das Anpassen des Flowchart muss jemand anderes machen. Da ich die SVG-Dateien nicht erstellt habe, kann ich sie schlecht ändern.
