### ISSUE TITLE
Check if do-it-like-babo is described that way:

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#358]
For OPSI and Docker, the installation procedure must be as described here. To be checked: 
https://ask.linuxmuster.net/t/umstellung-v7-auf-do-it-like-babo/3725/11

Bei OPSI und Docker muss der Ablauf der Installation wie hier geschrieben beschrieben sein. Zu überprüfen: https://ask.linuxmuster.net/t/umstellung-v7-auf-do-it-like-babo/3725/11

**Comment by cweikl** [comment]
OPSI and Docker not be supported anymore. Can be closed.
