### ISSUE TITLE
Close open and outdated issues 

### ISSUE THREAD

**Issue by toheine** [linuxmuster-docs/main#377]
After a long time I wanted to work on the documentation again. Now I have read the issues ... but I'm a little overwhelmed. May I suggest that we delete old 6.x-issues including the 6.x-milestone and create some new ones that contain concrete, small and big tasks?

**Comment by jolly-jump** [comment]
sure, now you have the rights. Go ahead and delete and sort and tag a gusto. Gracias.

**Comment by toheine** [comment]
Thanks for the rights and ... de nada ;-)
