### ISSUE TITLE
Further-Reading-Link (Sphinx) on README.rst

### ISSUE THREAD

**Issue by toheine** [linuxmuster-docs/main#380]
The link leads to an empty Wiki page. Should this link specifically refer to a Sphinx-article or should this be the link to the general Wiki?

**Comment by jolly-jump** [comment]
Don't know anymore. Guess it should point to: https://docs.linuxmuster.net/de/latest/appendix/contribute/index.html or some where down the path... this is from the time, when we had excessive documentation in the wiki

**Comment by toheine** [comment]
I think your link is a good target ;-). I will update the README.

**Comment by toheine** [comment]
Done!
