### ISSUE TITLE
Create bugfix documentation

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#387]
falls man händisch eingreifen muss
siehe hier: https://ask.linuxmuster.net/t/doku-braucht-evtl-bug-fix-abschnitt/5819

if manual intervention is needed

**Comment by toheine** [comment]
... erledigt, oder?

**Comment by jolly-jump** [comment]
Now I pushed the bugfix with #403 to the last agreed upon version: https://ask.linuxmuster.net/t/doku-braucht-evtl-bug-fix-abschnitt/5819/22?u=tobias
