### ISSUE TITLE
Dokumentation der Passwort Grundeinstellungen

### ISSUE THREAD

**Issue by lawilfried** [linuxmuster-docs/main#388]
In der Dolumentation könnte deutlicher werden, welche Grundeinstellungen vom global-admin gemacht werden können. Unter Einstellungen > Schuleinstellungen gibt es einen Reiter "Listenimport". Dort, was der Name nicht unbedingt vermuten lässt, können Einstellungen bezüglich der Passwortlänge und ob ein Zufallspasswort gewünscht wird, gemacht werden. Diese Einstellungen wirken auf die Datei /etc/linuxmuster/sophomorix/default-school/school.conf und umgekehrt. 
Wer sich gegen Zufallspasswörter entscheidet, bekommt per default das Erstpasswort "LinuxMuster!" Dieses befindet sich nicht in der school.conf. Eine Information darüber, wo man es abändern kann, wäre ganz nützlich.
Nicht klar ist, ob zusätzlich eine Anpassung mit dem samba tool nötig ist. Was die Passwortlänge angeht, wäre es für Passwörter mit mindestens 7 Zeichen folgender Befehl: 
`samba-tool domain passwordsettings set --min-pwd-length=7`

**Comment by jolly-jump** [comment]
hm, danke für den bugreport.
Das sind mehrere Probleme auf einmal. Manche davon müssen wir in Ask diskutieren, weil die dokumentation hier auch nicht Bescheid wissen kann.
Für die Dokumentation:
- [ ]  WebUI/Schulkonsole Benutzerhandbuch? Das ist ein großes Unterfangen, evtl. schon von netzint kopierbar?
- [ ] Standardpasswort "LinuxMuster!" dokumentieren, ok. Änderung dieser Einstellung - das könnte was für die Entwicklerdoku sein - oder auch hier. 

Die Verwendung von samba-tool hat definitiv nichts in der Doku zu suchen, das ist höchstens was für die Entwicklerdoku. 
Auch um mind. 7 Zeichen zu fordern - das gehört nicht in die Doku, m.E.
VG, Tobias

**Comment by jolly-jump** [comment]
hm, danke für den bugreport.
Das sind mehrere Probleme auf einmal. Manche davon müssen wir in Ask diskutieren, weil die dokumentation hier auch nicht Bescheid wissen kann.
Für die Dokumentation:
- [ ]  WebUI/Schulkonsole Benutzerhandbuch? Das ist ein großes Unterfangen, evtl. schon von netzint kopierbar?
- [ ] Standardpasswort "LinuxMuster!" dokumentieren, ok. Änderung dieser Einstellung - das könnte was für die Entwicklerdoku sein - oder auch hier. 

Die Verwendung von samba-tool hat definitiv nichts in der Doku zu suchen, das ist höchstens was für die Entwicklerdoku. 
Auch um mind. 7 Zeichen zu fordern - das gehört nicht in die Doku, m.E.
VG, Tobias

**Comment by lawilfried** [comment]
Hallo Tobias,

Am 10.07.2020, 22:29 Uhr, schrieb T. Küchel <notifications@github.com>:

> hm, danke für den bugreport.

es ging mir nur darum, sämtliche mir bekannten Punkte zu nennen, die  
Einfluss auf die grundsätzliche Passwortgestaltung haben oder haben  
könnten.

> Das sind mehrere Probleme auf einmal. Manche davon müssen wir in Ask  
> diskutieren, weil die dokumentation hier auch nicht Bescheid wissen kann.
>
> Für die Dokumentation:
>
> - [ ]  WebUI/Schulkonsole Benutzerhandbuch? Das ist ein großes  
> Unterfangen, evtl. schon von netzint kopierbar?
>
> - [ ] Standardpasswort "LinuxMuster!" dokumentieren, ok. Änderung dieser  
> Einstellung - das könnte was für die Entwicklerdoku sein - oder auch  
> hier.
>
>
>
> Die Verwendung von samba-tool hat definitiv nichts in der Doku zu  
> suchen, das ist höchstens was für die Entwicklerdoku.
> Auch um mind. 7 Zeichen zu fordern - das gehört nicht in die Doku, m.E.

Der Hinweis auf samba-tool stammt von Holger, und er hat ihn aus der Doku  
im Bereich "Migration". Ich habe den Befehl mit der "7" abgesetzt, weil  
auch in der Schuko in der Erläuterung die Zahl 7 auftaucht und ich dies  
gerne einheitlich hätte.

Wie letztendlich samba und sophomorix zusammenspielen, und ob es noch  
weitere Beteiligte bei der ganzen Passwortgeschichte gibt, weiß ich nicht,  
Ich meine aber, dass es durchaus hilfreich wäre, wenn es in der Doku eine  
zusammenhängende Erläuterung dazu gäbe.

Viele Grüße

Wilfried

**Comment by MachtDochNix** [comment]
- [ ] PW-Vorgaben bei Migration
- [ ] Passwort erlaubte Zeichen beschrieben?!
- [ ] Änderung der Passwortlänge sollte auf alle Fälle nachschlagbar sein. Ob allgemeine Doku?

**Comment by cweikl** [comment]
Have we addressed this issue? To be closed?

**Comment by lawilfried** [comment]
"PW-Vorgaben bei der Migration" sind nun evtl. nicht mehr so wichtig. Die anderen Punkte (Festlegung der Passwortlänge usw. und des Erstpasswortes) werden auch in der Doku zur V 7.1 nicht ausdrücklich erläutert.

**Comment by lawilfried** [comment]
"PW-Vorgaben bei der Migration" sind nun evtl. nicht mehr so wichtig. Die anderen Punkte (Festlegung der Passwortlänge usw. und des Erstpasswortes) werden auch in der Doku zur V 7.1 nicht ausdrücklich erläutert.

**Comment by lawilfried** [comment]
"PW-Vorgaben bei der Migration" sind nun evtl. nicht mehr so wichtig. Die anderen Punkte (Festlegung der Passwortlänge usw. und des Erstpasswortes) werden auch in der Doku zur V 7.1 nicht ausdrücklich erläutert.

**Comment by MachtDochNix** [comment]
Solange die Punkte nicht alle abschließend erklärt/bearbeitet sind, würde ich lawilfried zustimmen.

- [ ] PW-Vorgaben bei Migration
- [ ] Passwort erlaubte Zeichen beschrieben?
- [ ] Änderung der Passwortlänge sollte auf alle Fälle nachschlagbar sein. Ob allgemeine Doku?

**Comment by cweikl** [comment]
fixed with pull request #849
