### ISSUE TITLE
Continue button is not the real next step

### ISSUE THREAD

**Issue by toheine** [linuxmuster-docs/main#391]
The Continue-Button at the bottom of ... 
https://docs.linuxmuster.net/de/latest/getting-started/installoptions/install-from-scratch/buildserver.html
.. goes directly to the Migration-Step. But the real next step is the initial configuration at this site: https://docs.linuxmuster.net/de/latest/getting-started/setup.html#setup-using-selma-label

**Comment by MachtDochNix** [comment]
This is a known problem. The NEXT button always follows the next chapter that follows in the doctree. It can only be intercepted if the correct jump address is given as last line.
Maybe it helps if you set a new doctree as last line in the document. I don't know if this will mess up the menu bar.
####
Das ist ein bekanntes Problem. Der NEXT Button folgt immer den nächsten Kapitel das im doctree folgt. Lässt sich nur abfangen wenn als letzte Zeile die richtige Sprungadresse angegeben wird.
Vielleicht hilft es wenn in dem besagten Dokument als letztes ein neuer doctree gesetzt wird. Wobei ich nicht weiß, ob dadurch die Menuleiste durcheinander gewürfelt wird.

**Comment by MachtDochNix** [comment]
I'll check it out.
#####
Ich werde das mal überprüfen.

**Comment by MachtDochNix** [comment]
Unfortunately it does not work with additional doctree. :-(
#####
Mit zusätzlichem doctree funktioniert es leider nicht. :-(

**Comment by MachtDochNix** [comment]
Follow Me - image is a link to the next page
#####
Follow Me - Bild ist ein Link auf die nächste Seite

![grafik](https://user-images.githubusercontent.com/16538354/87454771-b827b400-c604-11ea-9af8-c51c97b654cf.png)

I've done that now:

- png - image (arrow_link.png) must be in the media folder of the page.

- in the RST file the following inserts the link: 

```
.. image:: media/link_arrow.png
   :target: ../../target.htlm
```

#####

Das habe ich jetzt hingekriegt:

png - Bild (arrow_link.png) muss sich im betreffenden media-Ordner der Seite befinden.

in der RST-Datei fügt folgendes den Link ein: 

```
.. image:: media/link_arrow.png
   :target: ../../target.htlm
```

TODO:

Colours of the picture still have to be adjusted.

Farben des Bildes müssen noch abgestimmt werden.

**Comment by MachtDochNix** [comment]
@cweikl,  @toheine 
Should I pursue this further?
Soll ich dieses so weiter verfolgen?

**Comment by toheine** [comment]
It's a good compromise. It seems pretty big, though. 40% of the size shown and I think it's great!
Es ist ein guter Kompromiss. Allerdings scheint es mir ziemlich groß. 40% der abgebildeten Größe und ich finde es super!

**Comment by MachtDochNix** [comment]
Then I will implement this and present it again.

Dann werde ich das mal so umsetzen und nochmal vorlegen.

**Comment by cweikl** [comment]
I agree, I think its is a very good compromise and we guide the readers throughout our documentation. 
Ist this necessary for all main chapters or also for the sub-chapters?

**Comment by MachtDochNix** [comment]
As a guide, these would be the pages in the schedule with decision and before the merger. Otherwise the Next and Previous buttons should work. This is how I imagine it now:

Als Orientierung wären das die Seiten im Ablaufplan mit Entscheidung und vor der Zusammenführung. Ansonsten sollten die Next und Previous Button funktionieren. So stelle ich mir das jetzt vor:

![grafik](https://user-images.githubusercontent.com/16538354/87811666-51ea9d80-c85f-11ea-9aea-08e07f2c97de.png)

Wenn es gefällt, dann nehme ich das auf meine ToDo

**Comment by toheine** [comment]
Finde ich gut so!

**Comment by jolly-jump** [comment]
Was ich nicht verstanden habe: sollen die Next und Previous buttons abgeschalten werden? Das kann man, glaube ich, tun. Aber nur global.
Ich finde dieses Karomuster schrecklich. YMMV

**Comment by MachtDochNix** [comment]
I would not turn off the Next and Previous buttons. Since they work in the chapters and their subchapters. So only the additional "Follow me" where they are needed. Since every taste should be met, then one way or another?

Ich würde die Next und Previous buttons nicht abschalten. Da sie in den Kapiteln und deren Unterkapitel ja funktionieren. Also nur die zusätzlichen "Follow me" dort wo sie gebraucht werden. Da jeder Geschmack getroffen werden soll, dann so oder so ähnlich?

![link_arrow](https://user-images.githubusercontent.com/16538354/87848344-a6cdf880-c8df-11ea-9659-cc0ec79dbae1.png)

**Comment by jolly-jump** [comment]
Ok.
Muuuch better.

Ok.
Viiiel besser.
:)

**Comment by MachtDochNix** [comment]
I'm glad, but it gets better. I'm on it right now!

Freut mich, aber es kommt noch besser. Bin gerade dran!

**Comment by MachtDochNix** [comment]
Betrifft: #391 und #392.

Ich bin am Verzweifeln. Irgendwie bekomme ich keine logische Verbindung hin mit der Menüstruktur und dem Ablaufplan.

Ich sehe das Problem, dass sich die Abfolge die das Menü vorgibt, für einen Neuling nicht erschließt. Führt sein erster Klick ihn nicht auf den Pfad der geführten Installation, dann ist er verloren/ zumindest verwirrt. 

Beispiel klickt mal folgendes:

[Installation: Übersicht]
[Vorüberlegungen]
[Erstkonfiguration]

############

Subject: #391 and #392.

I'm desperate. I can't get a logical connection with the menu structure and the flow chart.

I see the problem, that the sequence the menu gives is not obvious to a newbie. If his first click does not lead him to the path of the guided installation, he is lost/confused. 

Example clicks the following:

[Installation: Overview]
[Preliminary considerations]
[Initial configuration]

Just use the Next button or directly in the menu

Suddenly and unexpectedly he is finished with the installation and is supposed to accept clients.

I think it would be smarter to structure the menu exactly as the schedule says.

see: [1st part, 2nd part, 3rd part and 4th part ](https://docs.linuxmuster.net/de/latest/getting-started/overview.html)

What do you think?

Benutzt dabei mal nur den Next-Button oder direkt im Menü

Plötzlich und unerwartet ist er mit der Installation fertig und soll Clients aufnehmen.

Ich denke, es wäre schlauer das Menü genauso zu strukturieren, wie es der Ablaufplan vorgibt.

siehe: [1. Teil, 2. Teil, 3. Teil und 4. Teil ](https://docs.linuxmuster.net/de/latest/getting-started/overview.html)

Was meint ihr?

**Comment by toheine** [comment]
... ich habe jetzt 15 Minuten versucht das nachzustellen. Ich checke es nicht. Ich komme immer dahin wohin ich wil. Aber ich glaube fast, dass Du so tief drin bist ... dass es über unser Hinundher-Geschreibse eher schwierig ist. Wahrscheinlich kann ich Dir da im Alltag auch nicht direkt helfen. Wollen wir das auf der Herbsarbeitstagung angehen? In diesem Zusammenhang hätte ich auch einen Vorschlag an die Gruppe: Was hältst Du davon wenn wir zwar Datei-Namen, die Pull-Requests und von mir aus auch alles andere in englischer Sprache vollziehen ... aber einen Issue immer in der Sprache durchgehen, wie er eröffnet wurde? Das hin und her im English<>Deutsch verkompliziert es. Da ich aber das letzte Greenhorn der Riege bin ... ist das nur ein demütiger Vorschlage ;-)

**Comment by MachtDochNix** [comment]
Zur Sprache: Können wir gerne so händeln, würde dann aber weitergehen und sagen Issue nur noch in Deutsch. Zumindest solange bis sich ein nicht Deutsch-Kundiger in unsere Riege integriert.

@jolly-jump und @cweikl: Was meint ihr?

**Comment by cweikl** [comment]
First version of the rewritten menu and link structure of the documentation is online. Still has to be checked within each chapter.
Documentation of the usage of the new link structure to be written.

**Comment by cweikl** [comment]
This is not an issue in docu for v7.1, I think.
The workflow is documented in github wiki? 

Could we close this issue?
