### ISSUE TITLE
Missing description of hard disk resizing

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#392]
See: [Discurse on asks](https://ask.linuxmuster.net/t/from-scratch-installation-mit-anpassung-der-partitionen-des-servers/4686?u=machtdochnix)

**Comment by toheine** [comment]
Habe ich gerade durchgeführt und kann ich beschreiben. Du meinst:

Analyse mit 
pvs, vgs, lvs und lvdisplay, etc.

Durchführung mit 
lvextend -L+100G /dev/mapper/vg_srv-var
lvextend -L+200G /dev/mapper/vg_srv-linbo
lvextend -L+100G /dev/mapper/vg_srv-global
lvxetend -l +100%FREE/dev/mapper/vg_srv-default-school
... dann das Ganze noch mit einem --resizefs verpacken

Gibt es in diesem Zusammenhang für var und global Größen-Empfehlungen? (srv-default-school und linbo sind ja sehr schulspezifisch)

**Comment by toheine** [comment]
Ergänzung: / ist kein LVM ... hier wäre Vergrößerung per fdisk/gdisk notwendig.
Addition: / is not a LVM ... in this case enlargement via fdisk/gdisk would be necessary.

**Comment by MachtDochNix** [comment]
I would like to see all the possibilities already recorded. Where in the schedule should this best be placed?

Ich würde da schon alle Möglichkeiten aufgenommen wissen wollen. Wo sollte das im Ablaufplan am besten untergebracht werden?

**Comment by toheine** [comment]
My suggestion would be to put "System Administration" before the subtitle "Migration". Reason: During the migration data may be moved. If then the paritions are too small ... that would be a bad idea.

Mein Vorschlag wäre bei "Systemadministration" noch vor dem Untertitel "Migration". Grund: Bei der Migration werden evtl. Daten umgezogen. Wenn dann die Paritionen zu klein sind ... isses doof

![harddisk_resize_chapter](https://user-images.githubusercontent.com/22772813/87820192-f247be80-c86d-11ea-8edc-d3f416707c77.png)
Any other suggestions?

**Comment by MachtDochNix** [comment]
I was referring to this plan:

Ich bezog mich auf diesen Plan:

![grafik](https://user-images.githubusercontent.com/16538354/87853571-8fa50000-c90b-11ea-97ac-a715138f33d1.png)

It could be that there are differences in the installation targets (hypervisor, ...). I cannot estimate that, hence my question.

Es könnte sein, dass es Unterschiede bei den Installationszielen (Hypervisor, ...) gibt. Kann ich nicht abzuschätzen, daher meine Frage.

**Comment by toheine** [comment]
My suggestion is ... directly after VM-Import. 
Hard-disk-resizing needs two steps:

1. Resize the Hardrive or the virtual disk. This depends on the Hypervisior
2. Resize the LVMs and sda. The is independent from the hypervision in use ... (pretty sure).

I would document step two. Step one would have to be formulated by the authors, who also described the respective hypervisor and its installation. OK?

**Comment by MachtDochNix** [comment]
I worked it into the schedule once.
Now, if I were to process that further by linking the forks. Should I create empty pages at the relevant places right away? (With request for potential helpers)

Ich habe das mal in den Ablaufplan eingearbeitet.
Würde das jetzt mit der Verlinkung der Gabelungen weiter bearbeiten. Soll ich gleich leere Seiten an den betreffenden Stellen erstellen? (Mit Bitte um potentielle Mithelfer)

![grafik](https://user-images.githubusercontent.com/16538354/88059017-8e224480-cb64-11ea-879a-ef699ad226f6.png)

**Comment by jolly-jump** [comment]
Hi. Komme nur sporadisch dazu, das hier mitzuverfolgen, aber habe ich bei KVM das nicht einfach beim Hypervisor beschrieben, wie ich die Festplatten vergrößere und Chris hat das bei XCP-ng gemacht? 
Ah, ich verstehe, es geht um die scratch installation, ok. Das muss man in der Tat machen und ist bisher einfach dem Import der VMs mit inbegriffen und an der Stelle muss es rein.

**Comment by cweikl** [comment]
your diagramm describes the right way for necessary actions to be taken for hard disk resizing. I will describe the necessary actions for proxmox and XCP-ng. Could you give me an idea where the blank page has to be slotted in as I already started to rewrite the proxmox chapter as indictaed in #401 .

**Comment by cweikl** [comment]
Chapter currently integrated in current revesited menu structure an links. Text has to be written.

**Comment by cweikl** [comment]
I have written main parts of these chapter documentations. Could you please revise and give me some hinte, how to improve and fix mistakes. 
The descriptions how to resize hdd within proxmox, xcpng and kvm are still missing - how to link with these special arrows to next chapter for resizing vms?
Chris

**Comment by toheine** [comment]
@cweikl: I am so sorry that I did not bring in any content in the last months. I read your chapter today in the evening. And I prepare the chapter of resizing with proxmox on this weekend.

**Comment by toheine** [comment]
@cweikl: Now I've read your content and I think it is well written!  Ich prepare my proxmox-Test-Environment to describe how to resize the the virutal disks in proxmox tomorrow.

**Comment by cweikl** [comment]
@toheine: Thanks, could you please test the description how to resize OPNsense as I think that two or three steps have to be changed to succeed.

**Comment by toheine** [comment]
@cweikl: OK ... I'm on it. Today I set up my proxmox-test-environment from scratch again. I'm ready to make the tests in the next two days.

**Comment by cweikl** [comment]
Thank you !

**Comment by MachtDochNix** [comment]
I have just rebuilt my Test Environment #1 (Proxmox). Tomorrow it will continue here: [https://docs.linuxmuster.net/de/latest/getting-started/installoptions/install-on-proxmox/index.html#proxmox-einrichtung](https://docs.linuxmuster.net/de/latest/getting-started/installoptions/install-on-proxmox/index.html#proxmox-einrichtung)

Up to this step only small changes. I corrected them immediately in the documentation.

**Comment by toheine** [comment]
I updated the https://docs.linuxmuster.net/de/latest/getting-started/installoptions/install-on-proxmox/index.html#proxmox-einrichtung with code-blocks in my fork an created a pull request. Please check this. If this file is Ok, I can merge the code and continue with these two sites:
https://docs.linuxmuster.net/de/latest/getting-started/harddisk/hard-drive-size-vm.html
and
https://docs.linuxmuster.net/de/latest/getting-started/harddisk/hard-drive-size-opnsense-vm.html

**Comment by toheine** [comment]
... is merged ;-)

**Comment by toheine** [comment]
It may not be important but I think block devices are always named sd<xy> under Debian/Proxmox. In the documentation https://docs.linuxmuster.net/de/latest/getting-started/harddisk/hard-drive-size-vm.html the entries of lsblk is xvd<xy> (probably xenserver?). Do you have problems if I switch to sd<xy>?

**Comment by toheine** [comment]
I updated the chapter for resizing the OPNsense-Disk. Please check my suggestion and give me a feedback.

**Comment by toheine** [comment]
... is only a pull request at the moment ;-)

**Comment by MachtDochNix** [comment]
I have a question:

Wouldn't it be better to detach the chapter from the Installation menu?

Background to my thoughts: A change of size could always be necessary in the life of the administration. So wouldn't it fit better in System Administration.

For the procedure during the installation description we could then put jumps into this chapter. At the end of the chapter, we could jump back to the installation process.

**Comment by MachtDochNix** [comment]
Is done:

Description of hard disk enlargement of visualizers:

- [ ] Proxmox
- [ ] XCP-ng
- [ ] KVM

Description of customization on virtualized lmn servers:

- [ ] lmn7-opnsense
- [ ] lmn7-server
- [ ] lmn7-docker (note at lmn7-server)
- [ ] lmn7-opsi (note for lmn7-server)

Description for installation from scratch

- [ ] unnecessary?

**Comment by cweikl** [comment]
KVM still to be described

**Comment by MachtDochNix** [comment]
:-( XCP-ng missing:

source/getting-started/harddisk/hard-drive-size-xcp-ng.rst:: WARNING: image file not readable: getting-started/harddisk/media/
hdd-preparation-on-xcp-ng_0_1_vm-overview.png
hdd-preparation-on-xcp-ng_0_2_vm-overview.png
hdd-preparation-on-xcp-ng_0_3_vm-overview.png
hdd-preparation-on-xcp-ng_0_4_vm-overview.png
hdd-preparation-on-xcp-ng_0_5_vm-overview.png
hdd-preparation-on-xcp-ng_0_6_vm-overview.png
hdd-preparation-on-xcp-ng_1_vm-overview.png
hdd-preparation-on-xcp-ng_2_vm-select-hdd.png
hdd-preparation-on-xcp-ng_3_vm-hdd-resize.png
hdd-preparation-on-xcp-ng_4_vm-hdd-resize.png
hdd-preparation-on-xcp-ng_5_vm-hdd-status.png
hdd-preparation-on-xcp-ng_6_vm-start.png

**Comment by MachtDochNix** [comment]
Wonderful!

**Comment by cweikl** [comment]
What is your suggestion concerning KVM documentation?

**Comment by MachtDochNix** [comment]
I would look at the manual when I have my test proxmox up and running. My second test system is already waiting for it. :-)

**Comment by toheine** [comment]
KVM ist still missing, isn't it?

**Comment by cweikl** [comment]
Well, you're right. Could you fix it?

**Comment by toheine** [comment]
Thinkable ... but that does not happen overnight ;-)

**Comment by cweikl** [comment]
According to new decision  we will focus on from scratch documentation. Parts of resizing HDD are weiteren an can still be used in the new context.
