### ISSUE TITLE
Chapter about file permissions (getfacl, setfacl)

### ISSUE THREAD

**Issue by toheine** [linuxmuster-docs/main#400]
As an administrator you have to copy and move files on the system. The Problem are activated ACLs. I think we need a chapter about the tools getfacl, setfacl, sophomoriy-repair, ...

**Comment by toheine** [comment]
Is this procdure correct? ... :
- copy file to the directory you want
- change Linux/Unix-owner with chmod and chown (may be this is obsolete?)
- change ACLs ... e. g.
  - in /srv/samba/schools/default-school/share/program: 
    `setfacl [-R] -m g:s_default-school:r-x <file/directory>`
  - in /srv/samba/schools/default-school/teachers/<username>: 
    `setfacl [-R] -m u:<username>:rwx <file/directory>`

**Comment by jolly-jump** [comment]
argh. I have no idea.
All I know is, that everyone told me not to work with files on the server, 
at least, you need to use sophomorix-mount o.ä. to mount the samba file system locally.

**Comment by MachtDochNix** [comment]
Let's just ask @jeffbeck!

**Comment by MachtDochNix** [comment]
No answer! :-(

If we do not describe how to do this, then we should at least warn against it.

**Comment by cweikl** [comment]
With samba4 this issue has to be altered as samba manages acls.
To be closed.
