### ISSUE TITLE
Dead Link : Erstkonfiguration

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#405]
Problem auf Seite getting-started/setup.html

![grafik](https://user-images.githubusercontent.com/16538354/88154781-91224100-cc07-11ea-9b3b-86360dfd5ddd.png)

Ziel: https://docs.linuxmuster.net/de/latest/systemadministration/maintenance/migration.html

**Comment by jolly-jump** [comment]
darf ich das auch mit beheben?
ich habe noch einen fix, und kann das auch gleich mitmachen...

**Comment by jolly-jump** [comment]
hier #406 wäre der fix. einfach mergen

**Comment by MachtDochNix** [comment]
Natürlich du bist "head of doku"! Du darfst alle. ;-)
