### ISSUE TITLE
Nextcloud - AddOn external users

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#412]
Hi. 
The nextcloud doc should mention that it is the "nextcloud app" "external user" that is needed and maybe how to install it.
thanks

**Comment by cweikl** [comment]
Could you please give me some more information on app and external user. iI*m not sure what your mean, sorry.

**Comment by cweikl** [comment]
Is this still an issue?

**Comment by MachtDochNix** [comment]
Does Issue #376 not belong to this

**Comment by michaelkohls** [comment]
There is no app/addon "external user". Only the app "LDAP user and group backend " is required.
Everything necessary (ldap integration) is explained here: https://docs.linuxmuster.net/de/latest/external-services/nextcloud/index.html
In my opinion this issue could be closed.

**Comment by MachtDochNix** [comment]
Then i will closed this issue
