### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zefanja** [linuxmuster-docs/main#421]
Currently the docs are licensed under GPLv2 (some media files are CC-BY-SA 4.0). GPLv2 is mainly used for source code. Most documentations use a CC license. 

What is the main advantage(s) using GPLv2 for our docs compared to a CC license?

**Comment by MachtDochNix** [comment]
I don't think anyone has thought about that. (Except me in the graphics :-) ) 
GPLv2 looks very much like historical growth to me.
I would argue for a change to CC-BY-SA 4.0
#####
Ich denke, da hat sich niemand Gedanken darüber gemacht. (Außer ich bei den Grafiken :-) )
Die GPLv2 sieht mir ganz stark nach historisch gewachsen aus.
Ich würde für eine Umstellung auf die  CC-BY-SA 4.0 plädieren.

**Comment by cweikl** [comment]
I agree, we should switch to CC-BY-SA 4.0 for our documentation.
I think we still have not revised the original decision.

**Comment by MachtDochNix** [comment]
Do we see the Head of Doc as outvoted, or do we want to wait for his opinion? @jolly-jump 

What do we have to do to bring all our texts under the CC-BY-SA?

Does this only refer to the documentation of the 7 or do we want to do the same for the 6?

**Comment by cweikl** [comment]
We should declare our docs published under CC-BY-SA 4.0.
Which files have to be changed according to it?

**Comment by cweikl** [comment]
Upgraded license files (LICENSE.md) referencing CC-BY-SA 4.0

**Comment by MachtDochNix** [comment]
Well done!
