### ISSUE TITLE
Check if the naming pattern of the clients is exactly described.

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#432]
Example:

Room: verleihx
Computers: verleihx-pc01
Group: virt

workstation.csv
verleihx;verleihx-pc02;virt;...

[https://ask.linuxmuster.net/t/virtueller-client-bekommt-in-linbo-keine-gruppe/6434/8](https://ask.linuxmuster.net/t/virtueller-client-bekommt-in-linbo-keine-gruppe/6434/8)

**Comment by michaelkohls** [comment]
Es scheint ein paar Fallstricke bei der Wahl der Bezeichnungen für Raum und Gruppe zu geben. Dazu sagt die Doku momentan nichts.
Problem: Die Aufnahme von Clients wird innerhalb der Doku an mind. 4 verschiedenen Stellen beschrieben:
https://docs.linuxmuster.net/de/latest/getting-started/linuxclient.html#masterclient-als-neues-device
https://docs.linuxmuster.net/de/latest/getting-started/add-computer.html#rechneraufnahme-mit-der-schulkonsole
https://docs.linuxmuster.net/de/latest/clients/windows10clients/index.html#computer-uber-linbo-aufnehmen
https://docs.linuxmuster.net/de/latest/clients/windows10clients/index.html#uber-die-schulkonsole-zentral

Vorschlag: 
Das Kapitel "Installation/Rechneraufnahme mit der Schulkonsole" umbenennen in "Installation/Rechneraufnahme" und darin beide Varianten (Schulkonsole und Linbo) ordentlich beschreiben.
Beschreibungen aus Linux-Client und Windows-Client entfernen.

**Comment by MachtDochNix** [comment]
Guter Vorschlag!
