### ISSUE TITLE
Error source Highlight time difference between client and system time

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#456]

**Comment by MachtDochNix** [comment]
The supporter in me says to that: This is one of the biggest sources of error in our system. It's always a favourite. 

There should definitely be a hint box for this "... attention:: " 

Do we have one?

**Comment by cweikl** [comment]
still an issue? If so, where should we slot it in?

**Comment by MachtDochNix** [comment]
Am Donnerstag, 13. Oktober 2022, 18:46:09 CEST schrieb Chris Weikl:
> still an issue? If so, where should we slot it in?

I think it should be in the client ( registration) area because that's where 
the problems are. When joining the domain and later actions (login not 
possible, etc.) With the note that this should always be checked first.
