### ISSUE TITLE
Difference between project and course

### ISSUE THREAD

**Issue by aloisr** [linuxmuster-docs/main#458]
While working through the LMN7 I found out that there are "projects" and "courses". It is not clear to me what "projects" are good for where there are "courses".

When I create a "project", I can't do lessons with the "project group" (in 6.2 this is the case).

It would be good if the documentation would explain what the "courses" and "projects" are for.

Thanks a lot

Alois

**Comment by michaelkohls** [comment]
if the additions made are sufficient, this case can be closed
