### ISSUE TITLE
Change alternatives to options

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#480]
Change of the schedule:

Renaming alternatives to options.
These then with a sequential designation.

Example:
Option A Virtualization
Option A1 Proxmox
Option A2 XCP-ng
Option A3 ...

Option B Network setup
...

- [ ] Issue in linuxmuster-artwork open
- [ ] Change in the flowchart
- [ ] Change in the relevant chapter label by adding the option name (e.g. option A2).

**Comment by cweikl** [comment]
Well, according to the reorganisation of the docs we could drop this.
