### ISSUE TITLE
Change schedule

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#481]
Change schedule

The installation ends with the successful completion of the linuxpattern-install script.

[Add computer], [Create user] and [Linux client] move to the system administration.

But will be linked at the end of the installation description as a conclusion in the correct order.

- [x] Issue in linuxmuster-artwork open [Issue 23](https://github.com/linuxmuster/linuxmuster-artwork/issues/23)
- [ ] Changed in the flowchart
- [ ] Linked at the end of the installation description
- [ ] Added to systemadministration

**Comment by cweikl** [comment]
Do we still need this issue ? I do not know what it is all about.

**Comment by MachtDochNix** [comment]
Is this art, or can it go away? No, it can go!
