### ISSUE TITLE
do-it-like-babo wrong IP described

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#494]
noch eine Anmerkung zur OPNSense,
wenn man do-it-like-babo macht, ist die NoProxyGruppe auf 10.16.0.1 bis 10 eingestellt, gewollt wäre aber sicher 10.16.1.1 bis 10.
Danke für die Arbeit in der Doku!

**Comment by michaelkohls** [comment]
Auf welche Stelle der Doku bezieht sich das Problem?

**Comment by MachtDochNix** [comment]
Ursprung war dieser Thread in [ask](https://ask.linuxmuster.net/t/lmn7-do-it-like-babo-setup-probleme/6677/13)

So wie ich es damals verstanden habe, bezieht es sich auf eine fehlerhafte Einstellung in der WEB-UI der opensense.

**Comment by michaelkohls** [comment]
Also nach einem do-it-like-babo ist in der noproxy-Gruppe eingetragen: 10.16.0.1-10 + 10.16.1.1-3
Das erscheint mir auch okay so. 
In der Doku wird ja auch empfohlen den ersten PC (admin-PC) mit 10.16.0.10 zu konfigurieren. Das würde passen.
[https://docs.linuxmuster.net/de/latest/getting-started/installoptions/install-from-scratch/buildopnsense.html?highlight=10.16.0.10#konfiguration-der-opnsense](url)
Aus meiner Sicht gibt es keinen Änderungsbedarf in der Doku.

**Comment by MachtDochNix** [comment]
Bei do-it-like-babo sind doch aber die IP-Adressen mit der Netmask 255.240.0.0 aifgebaut und die Adressbereiche wie folgt fix eingeteilt:

10.16.1.1 - 10.31.254.254
10.31.1.1 - 10.46.254.254
usw.

Da passt doch die 10.16.0.1 bis 10.16.0.10 nicht rein. Oder denke ich falsch?
Eigentlich war do-it-like-babo ja hauptsächlich für Migrationen vorgesehen bzw. aus "Traditionspflege" für die Altvorderen. ;-)

**Comment by michaelkohls** [comment]
Das sehe ich anders. Man konnte bei der lml 6.x zwischen verschiedenen Netzen wählen:
10.16.0.0/12 oder 10.32.0.0./12 usw. Das ergibt im ersten Fall schon rein rechnerisch:
10.16.0.0 (Netzadresse) - 10.16.255.255(Broadcast) 
also Host-IP: 10.16.0.1 - 10.16.255.254
So steht es auch im alten Wiki: [((https://wiki.linuxmuster.net/archiv/dokumentation:handbuch:preparation:networktopology?s[]=10&s[]=31))]

Nun habe ich zur Prüfung des aktuellen Verhaltens von lml7 VM's aufgesetzt und mit do-it-like-babo laufen lassen. Dabei wird in der opnsense in die noproxy-Gruppe eingetragen: 10.16.0.1-10 + 10.16.1.1-3
Siehe auch Screenshot:
![do-it-like-babo](https://user-images.githubusercontent.com/74667054/105471424-02b47800-5c9b-11eb-98b7-0c4244233659.png)
10.16.1.1-3 sind für server + opsi + mail und 10.16.0.1-10 offensichtlich für admin-workstations

**Comment by MachtDochNix** [comment]
Da kannst du mal sehen, mit dem Alter schreitet die Betriebsblindheit weiter fort.

Habe es gerade an meinem Schulserver getestet. Ja du hast recht. Aber wie wohl die meisten, habe ich den 10.16.0.0 Bereich komplett ausgeblendet, weil es immer hieß ab 10.16.1.1.

Müssen wir nur in der Erinnerung behalten das die no-proxy-gruppe nach der letzendlichen Inbetriebnahme aufgeräumt werden muss. Gibt es dafür schon ein Ticket?

Also wird "do-it-like-babo wrong IP described"-Ticket hiermit geschlossen:

closed #494

**Comment by michaelkohls** [comment]
> Da kannst du mal sehen, mit dem Alter schreitet die Betriebsblindheit weiter fort.
Bei Lml 6.x wurde der Bereich 10.16.0.x irgendwie auch nicht so richtig verwendet, obwohl es sicher möglich war.

> Müssen wir nur in der Erinnerung behalten das die no-proxy-gruppe nach der letzendlichen Inbetriebnahme aufgeräumt werden muss. Gibt es dafür schon ein Ticket?

Gibt es wahrscheinlich nicht. Aber irgendwie ist das kaum von Bedeutung. Dazu müsste erstmal einer drauf kommen, dass es diesen Bereich gibt und es schaffen ein Gerät mit einer solchen Adresse in's grüne Netz zu bringen. Und das nur um am Proxy vorbei zu kommen. 
> 
> Also wird "do-it-like-babo wrong IP described"-Ticket hiermit geschlossen:
> 
> closed #494

Ich habe statt dessen 2 Stellen gefunden, wo 10.16.1.10 für admin-test-Station empfohlen wird, was suboptimal ist, weil die dann keinen Internetzugriff haben.
(https://docs.linuxmuster.net/de/latest/getting-started/network/preliminarysettings/index.html?highlight=10.16.1.10#beispiele)
https://docs.linuxmuster.net/de/latest/getting-started/prerequisites.html?highlight=10.16.1.10#standard-ip-adressen

Dazu könntest du ein Ticket aufmachen. Ich würde mich

**Comment by michaelkohls** [comment]
Ich sehe gerade, es gibt bereits ein Issue: #347
Dann nehmen wir das.
