### ISSUE TITLE
chapter freeradius seems to be revised

### ISSUE THREAD

**Issue by cweikl** [linuxmuster-docs/main#498]
As there is an ongoing disussion on how to install freeradius as a service for WLC or other services, the chapter has to be revised. the docu team decided to insert only officially supported solutions implemented by the developers. Therefore, the official way of installing freeradius on opnsense does not work at the moment. The second official was of using ist, is to install a docker container with an adapted freeradius installation. For the second way, there is currently no maintainer fpr a docker-container. Therefore the workaround to install freeradius in the server has to be shifted to the community wiki as a workaround description.

**Comment by MachtDochNix** [comment]
1000k Thanks!
