### ISSUE TITLE
chapter linux-client to be revised and extended

### ISSUE THREAD

**Issue by cweikl** [linuxmuster-docs/main#507]
this chapter is to be revised. https://docs.linuxmuster.net/de/latest/getting-started/linuxclient.html I miss "from scratch" here. First of all this is explaining, how to download a linux-cloop. I would point that out clearly. If there is some time to do it, I'd add a visual somewhere explaining that there are 2 ways to get to a working client (again "from scratch" vs. "importing cloops prepared by others).

**Comment by MachtDochNix** [comment]
Which milestone would you want to assign this to, Chris?
Shouldn't the two ways be better described in the System Administration section?

**Comment by cweikl** [comment]
Chapter for Linux Client rewritten according to the new package linuxmuster-linuxclient7.
