### ISSUE TITLE
howto: add printer as admin - linuxclient usage

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#51]
http://docs.linuxmuster.net/de/latest/howtos/printer/5-druckereinrichtung-clients.html#linux-clients

is wrong: 
standard behaviour should be using cups/client.conf -> SERVERIP as in the defaultcloop: http://www.linuxmuster.net/wiki/anwenderwiki:linuxclient:defaultcloop_16.04?s[]=client&s[]=conf

**Comment by cweikl** [comment]
ok, have to take a closer look how to describe this scenario as we reasume that every linux-client uses one of our cloops?

**Comment by jollyzsher** [comment]
Hi.
No, we don't have to assume a cloop. but we say: this is default behaviour:
1. create on the client: /etc/cups/client.conf with content "ServerName 10.16.1.1" (replace with your Server-IP )
2. optionally create on the client: /etc/cups/lpoptions with content "Default printername01"

Resulting in: No program listens to the cupsd on the client

**Comment by jolly-jump** [comment]
https://docs.linuxmuster.net/de/latest/systemadministration/printer/printer/4-drucker-auf-clients-einrichten.html#linux-clients

ist noch aktuell

**Comment by cweikl** [comment]
According to new linux-client package, the are hints in the documentation and the documentation for printers are also to be revised. There is an issue still active for.
