### ISSUE TITLE
Wrong net-id described 

### ISSUE THREAD

**Issue by michaelkohls** [linuxmuster-docs/main#516]
Im Kapitel getting-started/installoptions/install-on-kvm wird in den zwei Abschnitten "Optional: Umstellung des Netzbereichs" der optionale Netzbereich mit 10.16.1.0/12 bezeichnet. Das ist falsch, der Netzbereich ist 10.16.0.0/12. Nur die verwendeten IP-Adressen starten bei 10.16.1.1 usw.

**Comment by MachtDochNix** [comment]
Full acknowledgement! Ordne es dem nächsten Milestone zu.
