### ISSUE TITLE
add download-link PDF for single chapters

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#52]
global  PDF is far too difficult to find - and to big.

download per chapter it should be

**Comment by zefanja** [comment]
this could be a solution: http://stackoverflow.com/questions/15879276/any-way-to-generate-multiple-different-pdfs-from-single-sphinx-configuration

**Comment by zefanja** [comment]
@jollyzsher One more question: Do we want PDFs per manual (like one pdf for students, one for teachers, one for network administrators) or a PDF for every howto (like one PDF for xen, one for windows clients, ...)?

**Comment by jollyzsher** [comment]
I think, PDF for every howto would be nice and was the feature request.

**Comment by zefanja** [comment]
@jolly-jump Is this still necessary with the new structure? If not we can close this.

**Comment by jolly-jump** [comment]
sure, lets close it
