### ISSUE TITLE
Subsequent integration of linuxmuster-opsi

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#524]
Import description from the wiki:

[https://github.com/linuxmuster/linuxmuster-opsi/wiki/Integration](https://github.com/linuxmuster/linuxmuster-opsi/wiki/Integration)

**Comment by MachtDochNix** [comment]
I am considering whether we should not collect the links to the descriptions for such further instructions in one chapter. This would save us from redundancies.

**Comment by MachtDochNix** [comment]
@HappyBasher 

Hello Thomas,

I had a look,if there is a description for the post-installation for the optional docker host. Haven't found anything suitable in its wiki.

Kind regards Thorsten

**Comment by cweikl** [comment]
All links and documentations concerning OPSI will be placed in the Community Wiki. Support for OPSI and Docker VM will end soon.
