### ISSUE TITLE
Student import if possible with student ID

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#525]
Check if the import of school administration data using student ID is described. If no it should be described as default. In case the export is not possible, it can be pointed out that it is also possible without the ID.

**Comment by michaelkohls** [comment]
I Think it's sufficient described here: https://docs.linuxmuster.net/de/latest/user-management/manage-users/managewebui.html#export-von-schuler-und-lehrerliste-aus-dem-schulverwaltungsprogramm

**Comment by MachtDochNix** [comment]
Thank! closed #525
