### ISSUE TITLE
Kurzes Video zur initialen Orientierung für für die Mitarbeit an der Doku

### ISSUE THREAD

**Issue by toheine** [linuxmuster-docs/main#531]
Hallo zusammen,

wie besprochen würde ich ein kurzes Video erstellen, das den Einstieg für Mitwirkende an der Doku erleichtern soll. Initial würde ich folgende Punkte besprechen:

- Welche Beiträge kommen ins github-repo und welche kommen ins Wiki?
- Das Repo forken, eigenen Fork aktuell halten
- lokale Arbeiten: git, sphinx, make und Co
- Wichitige Guidlines: Namenskonvention, Struktur, ...

Fällt Euch noch ein wichtiger Aspekt ein? Wenn ja ... her damit ... wenn nein, formuliere ich aus den oben genannten Punkte die konkreten Inhalte und melde mich nochmal bevor ich das dann abdreh.

Greetings

Tobi

**Comment by michaelkohls** [comment]
Hallo Tobi!
Vielleicht auch ein kurzer Überblick über die Berechtigungen. Wie macht man einen Commit, wenn man noch keine Schreibrechte auf das Repo hat. Wen muss man fragen, wenn man was in's Wiki schreiben möchte?
Viele Grüße
Michael

**Comment by toheine** [comment]
Hallo Michael: Den Commit mache ich ja in meinen eigenen Fork. Da sollte ich dann die Rechte haben. Aus meinem Fork heraus erstelle ich dann den PR. Oder bin ich falsch? Wen muss man fragen, wenn man ins Wiki schreiben will nehm ich auf ... bzw. klär ich ab. Danke.

**Comment by MachtDochNix** [comment]
Wie erstelle ich ein Issue.
Was passiert mit einem Issue.
Was hat es mit den Milestones auf sich.

**Comment by toheine** [comment]
Nehm ich auf!

**Comment by michaelkohls** [comment]
> Hallo Michael: Den Commit mache ich ja in meinen eigenen Fork. Da sollte ich dann die Rechte haben. Aus meinem Fork heraus erstelle ich dann den PR. Oder bin ich falsch? 
Stimmt. Ich meinte auch PR. Bin da noch nicht so fit 
>Wen muss man fragen, wenn man ins Wiki schreiben will nehm ich auf ... bzw. klär ich ab. Danke.
Hat bei mir am Sonnabend Thorsten gemacht. Vielleicht gibt es noch andere.

**Comment by cweikl** [comment]
Hi Tobi,
hattest Du hier schon erste Abschnitte erstellt oder ruhte dies ?
VG

**Comment by cweikl** [comment]
no capcities
