### ISSUE TITLE
Anpassung von Servernamen werden nicht automatisch in postscript common übertragen.

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#532]
Hinweis einfügen in https://docs.linuxmuster.net/de/latest/clients/postsync/basics.html

Letzten Absatz hint einfügen/hervorheben das vor dem erneuten starten ein Image geschrieben werden muss.  https://docs.linuxmuster.net/de/latest/getting-started/linuxclient.html#masterclient-erstmalig-aufnehmen)

**Comment by cweikl** [comment]
can be closed according to the different content and structure of the above mentioned chapter.
