### ISSUE TITLE
m.E. Fehler in der Beschreibung der Vorgehensweise 

### ISSUE THREAD

**Issue by aloisr** [linuxmuster-docs/main#548]
Hallo Doku-Team,

hier:

https://docs.linuxmuster.net/de/latest/clients/windows10clients/index.html#domanenanbindung

unter "Manueller Domänen Join für Windows"

wird beschrieben wie man den Namen des Client ändert und gleichzeitig der Domäne bei tritt, Ich meine dass erst der Name geändert werden müsste und - nach einem Neustart - der Domäne beigetreten werden sollte.

Sollte die Beschreibung richtig sein und ich falsch liegen, dann ist dort trotzdem noch ein Fehler enthalten.

Scrollt man nämlich etwas weiter nach unten, dann steht unter "Hinweis" dass man nach dem Domänenbeitritt nicht mehr neu starten soll (das warum wird auch sehr gut erklärt). Aber oben unterhalb der Erklärung für die Namensänderung und den Domänenbeitritt steht dass man neu starten soll "OK → OK → Neustarten".

Gruß

Alois

**Comment by MachtDochNix** [comment]
@michaelkohls

Doesn't that fit with the topic #546?

**Comment by michaelkohls** [comment]
Mit #546 hat das nichts zu tun. Aber da ist in der Tat ein Widerspruch in den Aussagen.

Meiner Erfahrung nach kann man bei Win10 im Gegensatz zu früheren Versionen den Computernamen ändern und ohne vorherigen Neustart gleich der Domäne beitreten. Danach ist auf jeden Fall ein Neustart fällig.

Den Hinweis unterhalb von "Linbo-Image mit Domänenbeitritt" habe ich noch nie beachtet und trotzdem keine Probleme. Verstellte Maschinenpasswörter und damit verbundene Anmeldeprobleme kannte ich nur in der V6. Sollte vielleicht mal in ask diskutiert werden, ob das noch ne Rolle spielt. Falls nicht, kann der Hinweis weg.

**Comment by MachtDochNix** [comment]
Magst du mal eine Anfrage in Ask verfassen?

**Comment by michaelkohls** [comment]
Mach ich!

**Comment by MachtDochNix** [comment]
Thanks!

**Comment by michaelkohls** [comment]
Vorher checke ich noch schnell alte Threads. Vielleicht wurde ja schon mal darüber diskutiert.

**Comment by michaelkohls** [comment]
Interessante Aussage von Holger in ask: https://ask.linuxmuster.net/t/fehler-in-linuxmuster-client-adsso/5624/6
Man darf schon neu starten, aber dabei nicht syncen! Klingt logisch. Ist es doch passiert, muss die .macct weg und ein neues Image erzeugt und hochgeladen werden.

**Comment by MachtDochNix** [comment]
Und die von Dorien ergänzt dieses perfekt. Also sollten wir das auch so in der Dokuementation aufnehmen. Lass uns darüber heute abend mal reden. Danke für das kümmern.

**Comment by michaelkohls** [comment]
Änderungen sind gemerged. Kann vom mir aus geschlossen werden.
