### ISSUE TITLE
Beschreibung der Button im Bereich Klassenzimmer verkehrt?

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#567]
in der Doku auf der Seite:
>
> https://docs.linuxmuster.net/de/latest/classroom/webui-basics/index.html
>
> Steht bei der Erläuterung der kleinen Buttons bei den Kursen im Bereich
> Klassenzimmer was falsches, meine ich.
> Die Beschreibung der Icons ist genau verkehrt herum (oder?).
> Zuerst steht: "Sitzung neu starten" mit entsprechendem Icon und als
> Erläuterung:
> "Es handelt sich hier um den aktuellen Stand der Schüler wie er im AD zu
> finden ist. Das erstellen dauert einen Moment länger."
>
> Nö, oder?
> Da gehört der zwei Hinweis hin:
> "Die Sitzung wird wie vorgefunden gestartet. Es kann also sein, dass
> hier Schüler, die nicht mehr in diese Klasse gehören, noch angezeigt
> werden oder hinzugekommene fehlen. Man kann Schüler aus anderen Klassen
> hinzufügen und entfernen. Das bleibt dann solange, bis die Sitzung neu
> erstellt wird."

**Comment by MachtDochNix** [comment]
@michaelkohls 

Hallo Michael!

Die Meldung kam via Mail rein. Habe sie jetzt einfach mal als Issue Text hier rein geschmissen. Kannst du das bitte mal überprüfen.

Danke!

Thorsten

**Comment by michaelkohls** [comment]
Hallo Thorsten!
Da sind mir in der Tat die Beschreibungen durcheinander geraten. Werde ich gleich ändern.
Michael
