### ISSUE TITLE
howto: linuxclient cloop download

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#60]
in Absprache mit den Entwicklern akutalisieren.

- [x] an aktuellen Stand von linuxmuster-client-servertools anpassen
- [x] linuxmuster-client-servertools besser strukturieren https://github.com/linuxmuster/linuxmuster-client-servertools/pull/6
- [x] screenshots + dokumentation anpassen

siehe https://www.linuxmuster.net/wiki/dokumentation:techsheets:linuxmuster-client-servertools:start

**Comment by jollyzsher** [comment]
as soon as linuxmuster/linuxmuster-client-servertools#6 is accepted and merged, this one is done

**Comment by jolly-jump** [comment]
Hat sich mit Implementierung von linuxmuster-client-servertools in der v7 erledigt. 
Bugreports erfordern neue Issues
