### ISSUE TITLE
OpenVPN externe URL ist mißverständlich

### ISSUE THREAD

**Issue by garblixa** [linuxmuster-docs/main#618]
In der OpenVPN Konfiguration im Abschnitt `Server hinzufügen` steht im Punkt 3:

`Hostname oder IP-Adresse: server.linuxmuster.lan <hier sollte die externe URL der OPNsense® angegeben werden>`

Daß die externe URL der OPNsense angegeben werden muß ist mißverständlich. Erstens ist es keine URL, welche angegeben werden muß, sondern eine IP-Adresse oder Hostname.
Zweitens muß hier die Adresse oder IP-Adresse des LDAP Servers, also des linuxmuster.net Servers angegeben werden und nicht die Adresse der OPNsense. Am Besten also den Kommentar zwischen <> weglassen.

https://docs.linuxmuster.net/de/latest/systemadministration/openvpn/index.html#server-hinzufugen

Danke!

**Comment by cweikl** [comment]
Danke für den Hinweis. Das hieraus entstandende Missverständnis ist nachvollziehbar. Werde den commit so mergen.
Danke!
