### ISSUE TITLE
OPSI & Docker not being Part of Linuxmuster core: Docs to bei revised

### ISSUE THREAD

**Issue by cweikl** [linuxmuster-docs/main#636]
As developers indicate that OPSI & Docker VMs are not part of the core packages of Linuxmuster any.ore, the docs have to be revised accordingly. All parts containing hints and explanations have to be rewritten. Especially, for the setup warnings are necessary.
- introduction to be changed
- pics showing Services and options to be changed
- Setup descriptions and Pics are tobe changed

Attention
Packages for Setup and GUI are to be changed, as OPSI, Docker and Mail-Server Options are still to be removed

This is confirmed by the developers.

**Comment by cweikl** [comment]
I have already done following tasks:

- [ ] Restructuring of the complete index
- [ ] Restructuring if installation
- [ ] Restructuring of setup
- [ ] Restructuring of Migration
- [ ] Finished chapter setup
- [ ] Finished chapter migration
- [ ] Finished subchapter installation -> Proxmox
- [ ]

**Comment by MachtDochNix** [comment]
Docker and OPSI are now only listed in the SVGs , the overview pages about.rst and what-is-new-in-7-.rst. In my opinion, this issue can be closed.
