### ISSUE TITLE
Description of the ID in schueler.txt is missing.

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#650]
Only in the installation section is a brief mention. 

See ask thread [https://ask.linuxmuster.net/t/offene-benutzernamenvergabe/8212/9?u=machtdochnix](https://ask.linuxmuster.net/t/offene-benutzernamenvergabe/8212/9?u=machtdochnix)

**Comment by cweikl** [comment]
This is implemented in docs for 7.1: https://docs.linuxmuster.net/de/latest/user-management/manage-users/managewebui.html#pflege-der-schulerdatei
