### ISSUE TITLE
Description new feature linbo

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#651]
Nevertheless, there is a new feature: To avoid rebooting after a Linbo update, Linbo will perform a warm boot for future updates so that the updated Linbo is immediately available on the client.

However, as mentioned in the post above, you will have to restart the client again after this update for the new Linbo version to become active. In the future this will be omitted.

If the warmstart after update causes problems, you can get Linbo to stop this behavior by using the new kernel parameter warmstart=no [see README](https://github.com/linuxmuster/linuxmuster-linbo7#readme)

**Comment by cweikl** [comment]
v71 docu: having rewritten chapter using linbo4

- [ ] new features still missing

Where should we slot them in ?

**Comment by MachtDochNix** [comment]
I will revise the entire LINBO chapter. I think that besides a general description of the way of working, other small things are missing.

The naming of the innovations through LINBO4 in the introduction is already appropriate.
I would place detailed descriptions in the chapter at the appropriate place and highlight them with :hint:. These can then be removed in the next update. :-)

**Comment by cweikl** [comment]
new features listed in chapter LINBO4 in v7.2 docu
