### ISSUE TITLE
Explain entries in devices.csv

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#694]
Explain the names of the WebUI and the corresponding entries in devices.csv.

**Comment by cweikl** [comment]
In new docu for v7.1 the entries are described here: clients/client_templates/hardware_registration/index.html
Should we address further columns or the devices.csv directly ?

**Comment by MachtDochNix** [comment]
I think what is important for the WebUI are only the columns that are displayed. We have that.

It is different with the devices.csv.

What does a system call to the server console return?

[code]
man devices.csv
[/code]

If this would be helpful, I would suggest including this call. Then it is always up to date with the system.

**Comment by cweikl** [comment]
man devices.csv leads to a long output, declaring the use of all 15 fields.
Therefor we should only reference this code.

**Comment by MachtDochNix** [comment]
This was exactly what I meant and so we are always up to date if something changes. If the developers record this in the "man".
