### ISSUE TITLE
AD must always be the DNS for the trust position. 

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#703]
Feedback from support:

... ah crap: if I had known that I could have said right away that this doesn't work.
>> In the AD, the AD must always be the DNS for the trust position. This is also the case in a MS network (I had to learn painfully there: but no one has said anywhere prominent times ...)

Place the hint in the appropriate place.

**Comment by cweikl** [comment]
Do you know where to slot it in our documentation ?
