### ISSUE TITLE
Installation problems with too new OPNSense

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#708]
see: [Forum Post](https://ask.linuxmuster.net/t/probleme-mit-web-proxy-sso-config-file/8493/3?u=machtdochnix)

**Comment by cweikl** [comment]
This issue should be solved by thomas fix with new base 7.1 update:
See https://ask.linuxmuster.net/t/probleme-mit-linuxmuster-import-subnets/8501/14?u=cweikl

**Comment by MachtDochNix** [comment]
Yes, I think so too. So it can be closed.

But we should consider recording the version we tested with in the OPNSense installation instructions.
The best place would be here:

![opnsense](https://user-images.githubusercontent.com/16538354/153541475-618b1b2f-203a-473b-94f5-c7ee1b47e127.jpeg)

**Comment by cweikl** [comment]
I have tested several OPNsense Versions. The Key is that ssh connection from opnsense to server and vice versa needs to be set up an work, before you run setup. With the new fix from thomas the setup works successfully with opnsense 22.01.
