### ISSUE TITLE
Handbuch sophomorix: Kurzanleitung herauslösen.

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#72]
http://docs.linuxmuster.net/de/basiskurs/basiskurs/Anhang.html#sophomorix

sollte in ein Handbuch in der Hauptdoku oder als Verweis aufs Wiki. Hier dann löschen

**Comment by toheine** [comment]
Versteh ich nicht ... und Link läuft ins Leere.

**Comment by MachtDochNix** [comment]
Can this be closed?

**Comment by cweikl** [comment]
yes.

- Developer documentation can be found here: https://github.com/linuxmuster/sophomorix4/wiki
- no need or a short handbook.
