### ISSUE TITLE
Decide how to restructure the Basiskurs

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#73]
1. Es gibt den [alten Basiskurs (paedml 5)]( http://lehrerfortbildung-bw.de/netz/muster/linux/material/basis/doc/basiskurs.pdf) und wie ich sehe einen
[neuen Basiskurs (paedML 6)](http://lehrerfortbildung-bw.de/netz/muster/linux/material/basis/doc60/Basiskurs_Linux_6_201505.pdf)
Letzerer hat nur 88 Seiten im Vergleich zu > 250 Seiten.
Letzerer ist CC-BY-NC-SA lizensiert (ersterer vermutlich auch, auch
wenns nicht explizit ist, ->Autoren der ersteren?)

2. der Basiskurs alt wurde ja von Openoffice nach RST konvertiert und
lebt jetzt [hier](http://docs.linuxmuster.net/de/basiskurs/basiskurs.html)

Frage:
Soll der "Basiskurs" die Vorlage für eine Lehrerfortbildung sein, 
oder soll die Vorlage so sein: "zum selbst durcharbeiten, ggf. als Fortbildung verwendbar"
oder soll er nicht weiter gepflegt werden und nur Handbücher und Howtos geliefert werden?
Zum Dokument "Basiskurs" müsste man ja auch eine Schulungsumgebung dazuliefern
können (zumindest mit Linuxclient).

Vorschlag:
* Wir müssen uns die Mühe machen und ein Lastenheft aufschreiben, z.B.
anhand des bestehenden Basiskurses [1]:
  * "+" Grundlagen der Virtualisierung wie in [2] aber mit XEN
  * "-" "Wir nutzen die PaedML"
     -> ersetzen durch "Unterrichten mit der paedML [2]"
  * "+" Aufnahme Rechner Räume aus [2]
usw.

[1] http://lehrerfortbildung-bw.de/netz/muster/linux/material/basis/doc/basiskurs.pdf
[2] http://lehrerfortbildung-bw.de/netz/muster/linux/material/basis/doc60/Basiskurs_Linux_6_201505.pdf

**Comment by jollyzsher** [comment]
# Zusammenfassung
a. Wir wollen den Basiskurs inkl. Download-Schulungsumgebung behalten.
Dafür bieten wir Virtualbox-Images zum Download an. Ich schlage vor,
dass die auch unter http://pkg.linuxmuster.net/va/ liegen sollten.

b. Basis für die Weiterentwicklung ist die Version wie sie jetzt online
ist, also von paedML 5 abstammend.

c. Es gibt allerdings einiges zu tun, ein wenig Bügeln ist m.E. nicht
getan. Die logische Struktur des paedML 6 Basiskurses ist außerdem IMHO
besser -> beim Aktualisieren einbauen?

c2. Dazu sollten die HowTos aus dem Handbuch verlinkt sein: entweder darauf verweisen (Sprung zurück?) oder Dopplung durch einbauen (wie hardlinks). Auf alle Fälle sollte das PDF das ganze Material zum Download+Ausdrucken enthalten.

d. Wenn wir das nicht zeitnah leisten können -> Lastenheft schreiben und
als Auftrag bezahlen lassen?

e.  Welche Information soll zu Beginn stehen: Was steht auf der Homepage? Was wird
dort verlinkt? Was muss dementsprechend in einer Einleitung zum
Basiskurs stehen? Was muss dementsprechend in einer Einleitung zum
Handbuch stehen?
Das sind für mich mühsame Entscheidungen, wer das machen will: bitte melden.

**Comment by MachtDochNix** [comment]
What should be done with this issue?

**Comment by cweikl** [comment]
to be closed as we have a Basiskurs in our documentation for 6.2: https://docs.linuxmuster.net/de/basiskurs/index.html
If we should think of such a Basiskurs again for v7, a new issue has to be created.
