### ISSUE TITLE
howto: install opsi

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#76]
Opsi is completely missing from the documentation:

The sources:
http://www.linuxmuster.net/wiki/dokumentation:handbuch:addons:opsi
and
http://www.linuxmuster.net/wiki/dokumentation:handbuch:virtualisation:virtualappliance#opsi-va_integrieren
give hints what to do.
Also:
http://www.linuxmuster.net/flyspray/task/282
have technical detail.

**Comment by cweikl** [comment]
What about the OPSI VM for v7. In ask there was a survey about the usage of opsi within linuxmuster community and only two members indicated having used OPSI. discussion in ask: https://ask.linuxmuster.net/t/nachtraegliche-opsi-integration-moeglich/6069/26
If OPSI is thought to be developed further, we should think about a documentation. 
But this should only focus on Integration of OPSI VM into lmn7 ans the description of first steps for win10 software updates.
@

**Comment by cweikl** [comment]
Not still an issue, as Support for OPSI VM ends.
