### ISSUE TITLE
Term class work is missing

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#765]
Term class work is missing in the documentation, but is used in the help of the WebUI in the context of the exam mode.

**Comment by michaelkohls** [comment]
I think the issue no longer exists. The term is used and explained [here.](https://docs.linuxmuster.net/de/latest/classroom/exam-and-transfer.html#prufungsmodus-klassenarbeitsmodus)

**Comment by cweikl** [comment]
I thin so too
