### ISSUE TITLE
Note in doc v7.0 on linuxmuster-prepare

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#778]
Note in doc v7.0 on linux pattern-prepare in installation-from-scratch does not work. Note on using the OVAs.
[see`](https://ask.linuxmuster.net/t/linuxmuster-setup-laeuft-nicht-durch-ssh-verbindung-zur-firewall/8918/9?u=machtdochnix)

**Comment by cweikl** [comment]
still not necessary as docu of v7.1 is online
