### ISSUE TITLE
>>nomodeset<< parameter in the Client/Linbo chapter

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#782]
Description of the >>nomodeset<< parameter in the Client/Linbo chapter to fix graphics problems.

[see](https://ask.linuxmuster.net/t/client-haengt-beim-booten-von-linbo-bei-initializing-hardware/8959/4?u=machtdochnix)

**Comment by cweikl** [comment]
fixed with https://github.com/linuxmuster-docs/main/pull/804
