### ISSUE TITLE
client-server-tools not available in v7.1

### ISSUE THREAD

**Issue by cweikl** [linuxmuster-docs/main#797]
v7.1: docu is to corrected in chapter client

**Comment by MachtDochNix** [comment]
What should be done with this description?

The background to my question is the following thread in ask:

https://ask.linuxmuster.net/t/vorhalten-von-linux-client-images-durch-linuxmuster-net-der-neue-weg/7621/7?u=machtdochnix

Insight from this:

The client-server-tools are not maintained by anyone.
The package client-server-tools is no longer on a repro server.

The alternative is the package linuxpattern-linuxclient7 and this is already described in the documentation.

I would take out the whole chapter client-server-tools?

Comments requested!

**Comment by cweikl** [comment]
yes I agree. linuxmuster-client-servertools are no longer developed and support, so there is no need for such a description.

**Comment by jolly-jump** [comment]
weg damit! VG.

**Comment by cweikl** [comment]
closed with https://github.com/linuxmuster-docs/main/pull/803
