### ISSUE TITLE
lmn71-prepare fails during moving /var to new lvm device because of blocked files by lexcfs

### ISSUE THREAD

**Issue by LostInTranslation2** [linuxmuster-docs/main#807]
see
[https://ask.linuxmuster.net/t/neue-doku-zu-v7-1-als-beta-online-bitte-testen/8418/64](Post 1)
[https://ask.linuxmuster.net/t/luecke-in-der-dokumentation-fehler-beim-moving-var-im-lmn71-prepare/9115](Post 2)

According to communication with Thorsten the package lxcfs is deleted by lmn71-prepare either way (at the end of the script). But it is blocking the copying of /var earlier in the script. Therefore the deletion of lxcfs should be moved to the beginning of the script (before moving /var to new partition).

Temporary workaround: remove lxcfs manually before starting lmn71-prepare or at least stop lxcfs:

systemctl stop lxcfs.service

**Comment by cweikl** [comment]
This has been fixed in lmn-prepare. see: https://ask.linuxmuster.net/t/luecke-in-der-dokumentation-fehler-beim-moving-var-im-lmn71-prepare/9115/7
