### ISSUE TITLE
howto: integrate mailldap 

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#81]
https://github.com/linuxmuster-docs/howto_mailldap
is not yet finished. But it needs to be integrated into the documentation.

- [x] decide, whether it is an additional howto (linked in howtos.rst) or regular howto (linked in advisor.rst)
- [ ] research information on the current status (6.2) in the wiki etc.
- [ ] crosscheck with manual schulkonsole-admin
- [ ] crosscheck and update http://docs.linuxmuster.net/de/latest/release-information/schulkonsole.html#private-mailadresse-im-ldap
- [ ]  integrate into the documentation.

**Comment by cweikl** [comment]
This is old and refers to 6.2. In v7 we have a different ldap structure.
