### ISSUE TITLE
Remove usages of "create new image" in LINBO

### ISSUE THREAD

**Issue by dorianim** [linuxmuster-docs/main#810]
Hey everyone,

I just read the "Muster-Client" Docs when setting up a Pop!OS client and I am super happy that they are already updated for qcow2 and even have new screenshots, great work!

I wanted to note one thing though:
The function "create new image" in LINBO will be deprecated and removed soon. The new workflow is to use the "+" button in the webui:
![image](https://user-images.githubusercontent.com/30153207/191130140-a7300eb1-0a1c-4be7-a46e-7e090c3b9fcd.png)

to set a new image name for the new image in the start.conf. Once that is done, one can just start the client again and replace the "existing" image (the terminology will be changed).
Will be some time until this change happens, but I wanted to let you know about it :)

**Comment by cweikl** [comment]
Hi Dorian, 
is this new GUI "behaviour" now in action ?
Chris

**Comment by dorianim** [comment]
Not yet. It'll be changed in lmn 7.2

**Comment by dorianim** [comment]
But I think, it makes sense, to change the docs on this now, so anyone can get used to the new behaviour.

**Comment by cweikl** [comment]
I revised the chapter "Muster-Client" according to the new workflow. I am not really happy with it, as I cannot test it.
I changed chapter "Muster-Client aufsetze -  HWK" and "Betriebssystem installieren -> Linux-Client".
In chapter Linux-Client the pic 10-linux-client-ubu-install.png  seem to represent the "old linbo" menue - right ? Do oyu have an actual pic for me?

Please check the chapter if it represents the new workflow as you would expect it.

**Comment by dorianim** [comment]
I think, it's fine like that :)
the ui of linbo will change in v7.2, so the current screenshot is fine.

**Comment by cweikl** [comment]
ok thanks, then I close this issue an you reopen it if there are any issue when this new workflow is implemented in 7.2.
