### ISSUE TITLE
Firewall-Regel-Screenshot WAN -> "lokale Netze" 

### ISSUE THREAD

**Issue by Tw33ki** [linuxmuster-docs/main#813]
Es geht um folgenden Artikel: 
https://github.com/linuxmuster-docs/main/blob/master/source/external-services/nextcloud/nc-firewall.rst

Soll das Gerät aus dem WAN-netzwerk mit der OpenSense-Firewall auf dem Samba-Port kommunizieren ist folgendes Setting anzupassen: 
![grafik](https://user-images.githubusercontent.com/69896243/193803621-0c64f8f0-bacf-4637-a08b-852f70cf81b1.png)

_---
Ggf. entstehen sicherheitsnachteile, wenn Opensense z.B. exposed host ist, oder direkt mit WAN ins Internet verbudnen._

**Comment by cweikl** [comment]
Hallo,
könntest Du bitte etwas genauer angeben, an welcher Stelle Du o.g. Grafik ergänzt wissen willst ?
ttps://docs.linuxmuster.net/de/latest/external-services/nextcloud/nc-firewall.html - vor der Einrichtung des Portforwarding ?

Sicherheitsnachteile entstehen immer ...
Danke für Deine Hinweise.
VG

**Comment by Tw33ki** [comment]
Hi Cweikl,

ich denke ich würde hier einen passus einfügen: 
"wird die Nextcloud im WAN-netzwerk platziert, ist folgende Einstellung im WAN-Interface zu setzen:" 

Wir haben genau diese Situation - und mir ist es nach der Porteinrichtung aufgefallen, weil es nicht ging. Ob Ihr es in der Anleitung, vor oder nach der Porteinleitung ist für mich zweitrangig -> wollte nur darauf hiwneisen falls mal jemand auf das gleiche Problem stößt.
