### ISSUE TITLE
Remove description def-prof

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster-docs/main#825]
Windows client installation. Copy profiles, remove with def-prof. For this describe with GPO.

**Comment by cweikl** [comment]
Do you know how to do it with GPOs? I habe finished revision of win10 installation fpr v7.2 docu, but this part is still missing.

**Comment by cweikl** [comment]
I tested the workflow on a win10 client with the latest defprof version and it worked fine. According to this I described it as the standard workflow for v7.2 win10 client.
