### ISSUE TITLE
Problem mit der Gruppe @printing in CUPS

### ISSUE THREAD

**Issue by Tw33ki** [linuxmuster-docs/main#860]
Fügt man wie in der ANleitung beschrieben hier @printing hinzu, kann man unter windows Druckverwaltung keine Gerätetreiber als global-admin hinzufügen. Hier erhält man einen  IO-Error. 

https://docs.linuxmuster.net/de/latest/systemadministration/printer/add-printers-with-cups.html?highlight=%40printing#drucker-konfigurieren

**Comment by cweikl** [comment]
Könntest Du das Problem etwas genauer beschreiben ? 

- [ ] Wie verhält es sich auf Linux-Clients ?
- [ ] An welcher Stelle der Anleitung https://docs.linuxmuster.net/de/latest/systemadministration/printer/printers-windows-clients.html hakt es ?
- [ ] Hast Du einen Workaround ?
- [ ] Was gibt auf dem Windows Client folgender Befehl aus rpcclient 10.0.0.1 -U "LINUXMUSTER\global-admin" -c "enumdrivers 3" ?

**Comment by cweikl** [comment]
@michaelkohls : Könntest Du Dir das bitte nochmals ansehen, da ich hierzu keine Rückmeldung erhalten hatte.
Danke!

**Comment by michaelkohls** [comment]
@cweikl : Das mache ich. Kann aber paar Tage dauern... Schuljahresbeginn ...

**Comment by michaelkohls** [comment]
Jetzt ist zwar schon viel Zeit vergangen, aber endlich hatte ich Zeit mir das anzusehen. Grundsätzlich ist der global-admin kein Mitglied der Gruppe printing und kann daher auch nicht drucken. Auf das hinzufügen von Gerätetreibern hat das keinen Einfluss. Ich werde den Issue daher schließen.
