### ISSUE TITLE
Remove Rocket.Chat docs

### ISSUE THREAD

**Issue by dorianim** [linuxmuster-docs/main#869]
I think, the Rocket.Chat docs should be removed. They are out of date and Rocket.Chat does not support ldap properly anymore.

**Comment by cweikl** [comment]
ok, should we put it to our community wiki, just in case ldap support will be readopted in future by rocket.chat?

**Comment by dorianim** [comment]
I don't think, the effort is worth it. Rocket.Chat has become really unstable and hard to use, I doubt anyone really wants to use it.
