### ISSUE TITLE
rename remaing files with a german filename to English

### ISSUE THREAD

**Issue by zefanja** [linuxmuster-docs/main#88]
give all files an English filename

**Comment by toheine** [comment]
To Do: 
directory source ...
- [ ] /appendix/contribute/feedback/kommandozeile.rst
- [ ] /appendix/contribute/feedback/rekonfiguration.rst
- [ ] /appendix/contribute/feedback/technik.rst
- [ ] /appendix/contribute/feedback/media/virtualisiert.png
- [ ] /getting-started/contrib/einfachesn-netz.svg
- [ ] /getting-started/contrib/quellen.txt
- [ ] /getting-started/media/linbo-neustart.png
- [ ] and a lot of files under /locale/en/LC_MESSAGES

**Comment by MachtDochNix** [comment]
Ich habe mich der Sache angenommen.

**Comment by MachtDochNix** [comment]
Files /getting-started/contrib/einfachesn-netz.svg and /getting-started/contrib/quellen.txt seem not to be used anymore.
The same with all other files in /getting-started/contrib/. Renaming the folder does not generate any errors. Does anyone still need these? @cweikl @jolly-jump

**Comment by MachtDochNix** [comment]
@zefanja : Is there anything to consider when renaming the files in /locale/en/LC_MESSAGES?

**Comment by zefanja** [comment]
All the files under /locale/en are generated with this script: `updateLocales.sh`, so there is no need to rename the files. It should be enough to re-run the script.

**Comment by MachtDochNix** [comment]
If the script is called automatically (github) or must be triggered manually (local fork).

**Comment by MachtDochNix** [comment]
getting-started/media/linbo-neustart.png seem not to be used anymore. I renamed it anyway. Maybe we should clean up sometime?

**Comment by MachtDochNix** [comment]
After zefanja has answered the last question about the translation, this issue can be closed.
