### ISSUE TITLE
Layer3 - subnetting docs incorrect

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#95]
- [ ] see https://ask.linuxmuster.net/t/layer3-switch-einrichten/116 and fix downloadable switch configuration
- [ ] also: review the whole dokumentation
- [ ] also: https://ask.linuxmuster.net/t/seltsames-problem-mit-subnetting-ping/177/5 comment on the restrictive ACE
- [ ] also: https://ask.linuxmuster.net/t/sg-300-im-wiki-aenderungsbedarf/635 problem with generally recommending the Cisco (needs more configuration for larger schools )

Source: http://www.linuxmuster.net/wikiarchiv/dokumentation:addons:subnetting:start

**Comment by jolly-jump** [comment]
HI Christian, 
ich hab dir mal das Ticket zu geschoben, weil du die subnetting-kapitel in rST geschrieben hast.
Aufhänger sind zwar nicht die hier in dem Ticket geschriebenen Probleme aus der Community, sondern der Fakt, dass wir das Wiki verschoben haben und  aus:
http://www.linuxmuster.net/wikiarchiv/dokumentation:addons:subnetting:start
das meiste erstmal nicht von dir übernommen wurde.
Ich vermute, du hast alles damals neu geschrieben.
Sollen wir die Strategie zu subnetting in der Doku (v6.2 oder v7) mal in ask.linuxmuster.net diskutieren? oder hier?

als Anfang habe ich die Dateien mal englisch benannt.

VG, Tobias

**Comment by jolly-jump** [comment]
Hi nochmal,
subnetting in rST von dir vs. subnetting im wiki von Thomas:
Ich vermute, du hast ein "howto" geschrieben, in Gegensatz zur der Doku von Thomas, die zwar auch die Einrichtung eines Cisco SG300 beschreibt, vermutlich hatten wir aber irgendwie abgesprochen, dass es mehr eine Schritt-für-Schritt anleitung werden soll.

Daher diese Anmerkung: Wenn du weiter an der Doku arbeiten willst, würde ich vorschlagen, das was passt von Thomas zu übernehmen und das was nicht reinpasst, weil zu Umfangreich oder zu technisch oder was weiß ich... dass das in die github-Dokumentation gepackt wird, also als technische Doku zum Paket linuxmuster-base.

VG, Tobias

**Comment by cweikl** [comment]
Hi Tobi,
ich hatte in der Doku die Kapitel Postsync-Scripte, Drucker, Upgrade, Update, Backup, OpenVPN erstellt.
Subnetting war nicht dabei. Ich kann mich aber gerne im neuen Jahr darum kümmern ?!
VG
Christian

**Comment by jolly-jump** [comment]
HI Christian,

ok, hab rausgefunden, dass @ironiemix das Howto geschrieben hat, siehe https://github.com/linuxmuster-docs/howto_netzbrief_basics (das ist jetzt obsolet).
Aber das ändert nix: wenn du dich darum im neuen Jahr kümmern willst, gerne.

Wir sollten den Inhalt, falls du Fragen hast, aber bei ask diskutieren, hier verpass ich manchmal die Kommunikation.

VG, Tobias

**Comment by cweikl** [comment]
New Version #172 merged.
