### ISSUE TITLE
howto install on KVM host

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#96]
source:

  * http://www.linuxmuster.net/wiki/dokumentation:handbuch:virtualisation:reference.kvm
  * Hinweise auf Doku für andere Virtualisierer (anwenderwiki/Installationsleitfaden) oder keinen Virtualisierer (bare-metal/vanilla-installation)

target:

https://github.com/linuxmuster-docs/all-of-me/source/howtos/install-on-kvm

target technische Infos:

unterhalb von http://www.linuxmuster.net/wiki/dokumentation:techsheets

Hilfreiche Infos:

  * http://www.linuxmuster.net/wiki/dokumentation:sphinx
  * http://www.linuxmuster.net/wiki/dokumentation:handbuch_zum_handbuch

**Comment by zefanja** [comment]
Fixed by @morpweb latest PR?

**Comment by jolly-jump** [comment]
yes, indeed. closing
